import * as storage from '../storage.js';
import {normalizeRecord,exportRecordData} from '../core.js';
import {properties,propertyKey,csvCell} from '../workspace-context.js';
const zh=document.documentElement.lang.startsWith('zh'), L=(en,cn)=>zh?cn:en;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={title:['Management console','管理控制台'],'eyebrow':['PROPERTY RECORDS','房屋资料'],'workspace-link':['Receipt workspace','票据工作台'],'test-link':['Test report','测试报告'],refresh:['Refresh','刷新'],'source-label':['Data source','资料来源'],'search-label':['Search','搜索'],'user-label':['Uploaded by','上传人'],'status-label':['Review status','核对状态'],'export-csv':['Export table · CSV','导出总表 · CSV'],'original-title':['Original document','原始票据'],'evidence-title':['Source evidence & human edits','原文证据与人工修改'],'edit-record':['Edit and reconfirm','修改并重新确认'],'record-json':['Export record · JSON','导出记录 · JSON'],'original-download':['Download original','下载原件']};
for(const [id,t] of Object.entries(labels))$('#'+id).textContent=L(...t);
$('#full-json-title').textContent=L('View complete record JSON','查看完整记录 JSON');
$('#search').placeholder=L('Work, company, person or property','工作内容、公司、人员或房屋');
$('#data-source').options[0].text=L('Saved in this browser','此浏览器已保存记录');$('#data-source').options[1].text=L('Example portfolio · fictional','示例房屋组合 · 全部虚构');
$('#status-filter').options[0].text=L('All statuses','全部状态');$('#status-filter').options[1].text=L('User confirmed','用户已确认');$('#status-filter').options[2].text=L('Draft','草稿');
for(const b of document.querySelectorAll('[data-view]'))b.textContent=L(...{records:['All records','记录总表'],people:['People','用户'],properties:['Properties','房屋']}[b.dataset.view]);
$('#footer').textContent=L('Local management prototype. User confirmed means the uploader reviewed the record; it is not proof of authenticity or an administrator approval. Shared accounts, access controls and cloud storage are not connected.','本地管理原型。“用户已确认”表示上传者核对了记录，不代表真实性核验或管理员批准。共享账号、权限及云端存储尚未接入。');
let records=[],files=new Set(),assets={},view='records',selectedProperty=null,activeRecord=null,originalBlob=null,originalURL=null,loadVersion=0,recordVersion=0;
const unknown=()=>L('Not provided','未提供');
const person=r=>r.account?.display_name||L('Not recorded','未记录');
const status=r=>r.review.status==='confirmed'?L('User confirmed','用户已确认'):L('Draft','草稿');
const amount=r=>r.amount.total===null?unknown():`${r.amount.currency||L('Currency unknown','币种未知')} ${r.amount.total.toFixed(2)}`;
function selected(){const q=$('#search').value.trim().toLowerCase(),uid=$('#user-filter').value,st=$('#status-filter').value;return records.filter(r=>(!uid||(r.account?.id||'unassigned')===uid)&&(!st||r.review.status===st)&&(!selectedProperty||propertyKey(r)===selectedProperty)&&(!q||[r.service.summary,r.provider.organization_name,r.provider.person_name,r.property.id,r.property.service_address,person(r),r.document.number].join(' ').toLowerCase().includes(q)));}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function jsonDownload(r){download(new Blob([JSON.stringify(exportRecordData(r),null,2)],{type:'application/json'}),'domic-record.json');}
async function load(){const token=++loadVersion;$('#message').hidden=true;$('#export-csv').disabled=true;try{let next,nextFiles,nextAssets={};if($('#data-source').value==='demo'){const res=await fetch('examples.json');if(!res.ok)throw Error(L('Example portfolio could not load.','示例资料加载失败。'));const data=await res.json();next=data.records.map(normalizeRecord);nextAssets=data.originals;nextFiles=new Set(Object.keys(nextAssets));}else{[next,nextFiles]=await Promise.all([storage.all(),storage.fileIds()]);}if(token!==loadVersion)return;records=next;files=nextFiles;assets=nextAssets;const old=$('#user-filter').value,us=new Map(records.map(r=>[r.account?.id||'unassigned',person(r)]));$('#user-filter').innerHTML=`<option value="">${L('All people','全部用户')}</option>`+[...us].map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');if(us.has(old))$('#user-filter').value=old;render();}catch(e){if(token!==loadVersion)return;$('#message').hidden=false;$('#message').textContent=e.message;records=[];files=new Set();assets={};$('#export-csv').disabled=true;$('#content').innerHTML='';$('#stats').innerHTML='';$('#results-count').textContent='';}}
function render(){const data=selected(),allGroups=new Set(records.map(propertyKey));$('#scope-note').textContent=$('#data-source').value==='demo'?L('Fictional accounts and records for exploring the structure. These are separate from your uploaded files and are not OCR results.','虚构账户和记录用于查看管理结构；与已上传文件分开，不代表 OCR 提取结果。'):L('Shows only files saved in this browser. This page cannot see other customers or devices; no shared backend or administrator authentication is connected.','只显示此浏览器保存的资料；看不到其他客户或设备的信息，尚未接入共享后端和管理员登录。');$('#stats').innerHTML=[[records.length,L('Records','记录')],[allGroups.size,L('Property groups','房屋分组')],[new Set(records.map(r=>r.account?.id||'unassigned')).size,L('Uploaders','上传人')],[records.filter(r=>r.review.status==='confirmed').length,L('User confirmed','用户已确认')]].map(([v,l])=>`<div><strong>${v}</strong><span>${l}</span></div>`).join('');$('#breadcrumb').innerHTML=selectedProperty?`<button class="link-button" id="clear-property">${L('All properties','全部房屋')}</button> / ${esc(data[0]?.property.id||unknown())}`:'';if($('#clear-property'))$('#clear-property').onclick=()=>{selectedProperty=null;render();};$('#export-csv').disabled=!data.length;$('#results-count').textContent=`${data.length} ${L('matching records','条匹配记录')}`;
if(!data.length){$('#content').innerHTML=`<div class="empty"><h2>${L('No records here yet','这里尚无记录')}</h2><p>${L('Upload and confirm a document, change the filters, or explore the fictional portfolio.','上传并确认一份票据、调整筛选，或查看虚构房屋示例。')}</p><a class="button primary" href="../">${L('Add a document','添加票据')}</a></div>`;return;}
if(view==='people'&&!selectedProperty){const groups=new Map();for(const r of data){const id=r.account?.id||'unassigned';if(!groups.has(id))groups.set(id,[]);groups.get(id).push(r);}$('#content').innerHTML=`<div class="table-wrap"><table><thead><tr>${[L('Uploader','上传人'),L('Role','身份'),L('Properties','房屋'),L('Records','记录'),L('Action','操作')].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${[...groups].map(([id,rs])=>`<tr><td>${esc(person(rs[0]))}<small>${esc(id)}</small></td><td>${esc(rs[0].account?.role||unknown())}</td><td>${new Set(rs.map(propertyKey)).size}</td><td>${rs.length}</td><td><button class="link-button" data-person="${esc(id)}">${L('View properties','查看房屋')}</button></td></tr>`).join('')}</tbody></table></div>`;for(const b of document.querySelectorAll('[data-person]'))b.onclick=()=>{$('#user-filter').value=b.dataset.person;setView('properties');};}
else if(view==='properties'&&!selectedProperty){const groups=new Map();for(const r of data){const key=propertyKey(r);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}$('#content').innerHTML=`<div class="property-grid">${[...groups].map(([key,rs])=>{const p=properties.find(p=>p.uid===rs[0].property.uid);return `<article class="property-card"><span class="tag ${p?'':'amber'}">${p?L('Linked property','已关联房屋'):L('Unlinked record','尚未关联')}</span><h2>${esc(rs[0].property.id||unknown())}</h2><p>${esc(p?.address||rs[0].property.service_address||unknown())}</p><p>${L('Owner','房主')}: ${esc(p?.owner||unknown())}</p><p>${rs.length} ${L('records','条记录')} · ${new Set(rs.map(r=>r.account?.id||'unassigned')).size} ${L('uploaders','名上传人')}</p><button class="button" data-property="${esc(key)}">${L('Open property history','查看房屋历史')}</button></article>`;}).join('')}</div>`;for(const b of document.querySelectorAll('[data-property]'))b.onclick=()=>{selectedProperty=b.dataset.property;render();};}
else {let banner='';if(selectedProperty){const p=properties.find(p=>p.uid===data[0].property.uid);banner=`<div class="property-banner"><p>${L('PROPERTY HISTORY','房屋历史')}</p><h2>${esc(data[0].property.id||unknown())}</h2><p class="muted">${esc(p?.address||data[0].property.service_address||unknown())} · ${L('Owner','房主')}: ${esc(p?.owner||unknown())}</p></div>`;}$('#content').innerHTML=banner+table(data.slice().sort((a,b)=>(b.service.date||'').localeCompare(a.service.date||'')));for(const b of document.querySelectorAll('[data-record]'))b.onclick=()=>openRecord(b.dataset.record);}}
function table(data){return `<div class="table-wrap"><table><thead><tr>${[L('Service date','服务日期'),L('Property / work','房屋／工作'),L('Company / worker','公司／施工者'),L('Total','总额'),L('Uploaded by','上传人'),L('Review / original','核对／原件'),L('Action','操作')].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr><td>${esc(r.service.date||unknown())}<small>${esc(r.document.type)}</small></td><td class="work"><strong>${esc(r.property.id||unknown())}</strong><br>${esc(r.service.summary||unknown())}</td><td>${esc(r.provider.organization_name||r.provider.name||unknown())}<small>${esc(r.provider.person_name||unknown())}</small></td><td>${esc(amount(r))}<small>${esc(r.amount.payment_status)}</small></td><td>${esc(person(r))}${r.account?.is_demo?'<small>Demo</small>':''}</td><td><span class="tag ${r.review.status==='draft'?'amber':''}">${status(r)}</span><small>${files.has(r.id)?L('Original attached','原件已附'):L('Original unavailable','原件不可用')}</small></td><td><button class="link-button" data-record="${esc(r.id)}">${L('Open record','查看记录')}</button></td></tr>`).join('')}</tbody></table></div>`;}
function setView(v){view=v;selectedProperty=null;for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-current',b.dataset.view===view?'page':'false');render();}
const detailPaths=[['Uploaded by','上传人',r=>person(r)],['Property','房屋',r=>r.property.id],['Property link','房屋关联',r=>r.property.uid],['Work summary','服务描述',r=>r.service.summary],['Type of change','变更类型',r=>r.service.change_type],['Service date','服务日期',r=>r.service.date],['Company','公司',r=>r.provider.organization_name],['Actual worker','实际施工者',r=>r.provider.person_name],['Provider display name','服务商显示名称',r=>r.provider.name],['Service address','施工地址',r=>r.property.service_address],['Home system / area','房屋系统／部位',r=>`${r.service.category} / ${r.service.location||unknown()}`],['Total','总额',amount],['Payment / completion','付款／完工',r=>`${r.amount.payment_status} / ${r.service.completion_status}`],['Document type / number','单据类型／编号',r=>`${r.document.type} / ${r.document.number||unknown()}`],['Issue date','开票日期',r=>r.document.issue_date],['Provider phone / address','服务商电话／地址',r=>[r.provider.phone,r.provider.address].filter(Boolean).join(' / ')],['Equipment / serial','设备／序列号',r=>[r.details.asset_model,r.details.asset_serial].filter(Boolean).join(' / ')],['Warranty / permit','保修／许可',r=>[r.details.warranty,r.details.permit_number].filter(Boolean).join(' / ')],['Notes','备注',r=>r.notes],['Line items','费用明细',r=>r.items.map(i=>`${i.description||unknown()} · ${i.amount??unknown()}`).join('\n')],['Review status','核对状态',status],['Saved / updated','保存／更新时间',r=>`${r.created_at||unknown()} / ${r.updated_at||unknown()}`],['Original filename','原件文件名',r=>r.source.name]];
async function openRecord(id){const recordToken=++recordVersion;activeRecord=records.find(r=>r.id===id);if(!activeRecord)return;const r=activeRecord;$('#record-title').textContent=r.service.summary||L('Record details','记录详情');$('#record-state').textContent=status(r);$('#record-fields').innerHTML='<table>'+detailPaths.map(([en,cn,get])=>`<tr><th>${L(en,cn)}</th><td>${esc(get(r)||unknown())}</td></tr>`).join('')+'</table>';$('#full-json').textContent=JSON.stringify(exportRecordData(r),null,2);$('#record-evidence').textContent=JSON.stringify({edited_fields:r.review.edited_fields,missing_fields:r.review.missing_fields,evidence:r.evidence,extraction:r.extraction},null,2);$('#edit-record').hidden=$('#data-source').value==='demo';$('#edit-record').href='../'+(zh?'zh.html':'')+'?record='+encodeURIComponent(id);$('#original').textContent=L('Loading original…','正在读取原件…');$('#original-status').textContent='';$('#original-download').disabled=true;if(originalURL)URL.revokeObjectURL(originalURL);originalURL=null;originalBlob=null;$('#record-dialog').showModal();try{let loadedBlob;if(assets[id]){if(!/^\.\.\/round2\/files\/[a-z0-9-]+\.(pdf|png)$/i.test(assets[id]))throw Error('Invalid example path');const res=await fetch(assets[id]);if(!res.ok)throw Error('Original unavailable');loadedBlob=await res.blob();}else loadedBlob=await storage.file(id);if(recordToken!==recordVersion||activeRecord?.id!==id||!$('#record-dialog').open)return;originalBlob=loadedBlob;if(!originalBlob)throw Error(L('The original is missing. Structured details are still available.','原件不可用，结构化资料仍可查看。'));originalURL=URL.createObjectURL(originalBlob);const el=document.createElement(originalBlob.type==='application/pdf'?'iframe':'img');el.src=originalURL;if(el.tagName==='IFRAME')el.title=L('Original PDF','原始 PDF');else el.alt=L('Original uploaded receipt','上传的原始票据');$('#original').replaceChildren(el);$('#original-status').textContent=L('Original linked to this exact record.','这是与本条记录关联的原件。');$('#original-download').disabled=false;}catch(e){if(recordToken===recordVersion&&activeRecord?.id===id&&$('#record-dialog').open)$('#original').textContent=e.message;}}
$('#close-dialog').onclick=()=>$('#record-dialog').close();$('#record-dialog').onclose=()=>{recordVersion++;if(originalURL)URL.revokeObjectURL(originalURL);originalURL=null;activeRecord=null;};$('#record-json').onclick=()=>activeRecord&&jsonDownload(activeRecord);$('#original-download').onclick=()=>{if(originalBlob&&activeRecord)download(originalBlob,activeRecord.source.name||'receipt');};
$('#export-csv').onclick=()=>{const data=selected(),columns=[['record_id',r=>r.id],['uploaded_by',person],['user_id',r=>r.account?.id],['property_id',r=>r.property.uid],['property_name',r=>r.property.id],['service_address',r=>r.property.service_address],['service_date',r=>r.service.date],['work_summary',r=>r.service.summary],['change_type',r=>r.service.change_type],['company',r=>r.provider.organization_name],['worker',r=>r.provider.person_name],['total',r=>r.amount.total],['currency',r=>r.amount.currency],['payment_status',r=>r.amount.payment_status],['completion_status',r=>r.service.completion_status],['document_type',r=>r.document.type],['document_number',r=>r.document.number],['issue_date',r=>r.document.issue_date],['review_status',r=>r.review.status],['original_filename',r=>r.source.name]];const csv=[columns.map(x=>csvCell(x[0])).join(','),...data.map(r=>columns.map(([,fn])=>csvCell(fn(r))).join(','))].join('\r\n');$('#csv-preview').value=csv;$('#csv-title').textContent=L('Export table','导出总表');$('#csv-note').textContent=L('Review the CSV below. Download it, or select and copy the contents if this browser does not support downloads. Only the currently filtered records are included.','下方是实际 CSV 内容。可以下载；如果浏览器不支持下载，可全选并复制。只包含当前筛选结果。');$('#csv-preview-label').textContent=L('CSV contents','CSV 内容');$('#csv-select').textContent=L('Select all','全选');$('#csv-download').textContent=L('Download CSV','下载 CSV');$('#csv-dialog').showModal();};
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>setView(b.dataset.view);$('#data-source').onchange=()=>{selectedProperty=null;$('#user-filter').value='';load();};$('#refresh').onclick=load;$('#search').oninput=render;$('#user-filter').onchange=()=>{selectedProperty=null;render();};$('#status-filter').onchange=render;window.addEventListener('focus',()=>{if(!$('#record-dialog').open)load();});await load();

$('#csv-close').onclick=()=>$('#csv-dialog').close();$('#csv-select').onclick=()=>{$('#csv-preview').focus();$('#csv-preview').select();};$('#csv-download').onclick=()=>download(new Blob(['\uFEFF'+$('#csv-preview').value],{type:'text/csv;charset=utf-8'}),'domic-records.csv');
