'use strict';
const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const allowedLanguages=['zh','en','both'];
let lang=new URLSearchParams(location.search).get('lang')||storage.get('scholastic-guide-language')||'zh';
if(!allowedLanguages.includes(lang))lang='zh';
function bilingual(zh,en){const outer=document.createElement('span');outer.className='bi';for(const [l,t] of [['zh-CN',zh],['en',en]]){const s=document.createElement('span');s.lang=l;s.textContent=t;outer.append(s)}return outer}
function setLanguage(value){lang=value;document.body.dataset.language=value;document.documentElement.lang=value==='en'?'en':'zh-CN';document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===value)));storage.set('scholastic-guide-language',value);const url=new URL(location.href);url.searchParams.set('lang',value);history.replaceState(null,'',url);document.title=value==='en'?'Scholastic 2027 Preparation Guide · TimeMemo':'Scholastic 2027 参赛准备指南 · TimeMemo'}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));setLanguage(lang);
const w=document.getElementById('pixel-width'),h=document.getElementById('pixel-height'),result=document.getElementById('pixel-result'),shape=document.getElementById('pixel-shape');
function checkPixels(){const width=Number(w.value),height=Number(h.value);const valid=w.value!==''&&h.value!==''&&Number.isInteger(width)&&Number.isInteger(height)&&width>0&&height>0&&width<=100000&&height<=100000;result.replaceChildren();result.classList.toggle('fail',!valid||Math.min(width,height)<2700);w.setAttribute('aria-invalid',String(!w.validity.valid||w.value===''));h.setAttribute('aria-invalid',String(!h.validity.valid||h.value===''));if(!valid){result.append(bilingual('请输入 1–100000 之间的整数像素。','Enter whole-number pixel dimensions from 1 to 100,000.'));shape.style.visibility='hidden';return}shape.style.visibility='visible';const short=Math.min(width,height),ok=short>=2700;result.append(bilingual(ok?'✓ 像素尺寸达标':'× 像素尺寸不足',ok?'✓ Pixel dimensions meet the threshold':'× Pixel dimensions are too small'));const sub=document.createElement('small');sub.append(bilingual('短边 '+short.toLocaleString()+' px；要求至少 2700 px。','Shorter side: '+short.toLocaleString()+' px; minimum: 2,700 px.'));result.append(sub);if(!ok){const note=document.createElement('small');note.append(bilingual('请找原图或重新拍摄；不要靠拉伸小图补足。','Use the original or reshoot; do not stretch a small image to qualify.'));result.append(note)}const scale=Math.min(160/width,115/height);shape.style.width=width*scale+'px';shape.style.height=height*scale+'px'}
w.addEventListener('input',checkPixels);h.addEventListener('input',checkPixels);checkPixels();
const checks=[...document.querySelectorAll('[data-check]')];let saved={};try{saved=JSON.parse(storage.get('scholastic-guide-checks')||'{}')||{}}catch{}for(const c of checks)c.checked=saved[c.dataset.check]===true;
function progress(){const n=checks.filter(c=>c.checked).length;document.getElementById('check-progress').replaceChildren(bilingual(n+' / '+checks.length+' 项已勾选',n+' / '+checks.length+' items checked'))}
function saveChecks(){storage.set('scholastic-guide-checks',JSON.stringify(Object.fromEntries(checks.map(c=>[c.dataset.check,c.checked]))));progress()}
checks.forEach(c=>c.addEventListener('change',saveChecks));document.getElementById('reset-checks').addEventListener('click',()=>{checks.forEach(c=>c.checked=false);saveChecks()});progress();document.getElementById('print-guide').addEventListener('click',()=>window.print());
