(function(){if(!('speechSynthesis' in window))return;var S=window.speechSynthesis,q=[],bar;
var st=document.createElement('style');st.textContent='.say{border:1px solid #a9bdb6;background:#fff;color:#183437;border-radius:999px;font:500 12px/1 "IBM Plex Sans","Noto Sans SC",sans-serif;padding:4px 10px;cursor:pointer;margin-left:10px;vertical-align:middle}.say:hover{border-color:#166b61;color:#166b61}h2 .say{font-size:12px}.sub-body>.say{margin:8px 0 2px}.say-bar{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:80;background:#183437;color:#fff;border-radius:999px;padding:8px 10px 8px 18px;display:none;gap:12px;align-items:center;font:14px "IBM Plex Sans","Noto Sans SC",sans-serif;box-shadow:0 8px 24px rgba(0,0,0,.25)}.say-bar button{border:0;border-radius:999px;background:#fff;color:#183437;padding:5px 12px;font:inherit;cursor:pointer}';document.head.appendChild(st);
bar=document.createElement('div');bar.className='say-bar';bar.innerHTML='<span></span><button type="button">■</button>';document.body.appendChild(bar);bar.querySelector('button').onclick=stop;
function L(){return document.body.dataset.language==='en'?'en':'zh'}
function voice(l){var vs=S.getVoices(),re=l==='en'?/^en(-|_)?/i:/^(zh|cmn)(-|_)?/i,c=vs.filter(function(v){return re.test(v.lang)});var p=c.filter(function(v){return l==='en'?/en.US/i.test(v.lang):/(CN|Hans)/i.test(v.lang)});return p[0]||c[0]||null}
function stop(){q=[];S.cancel();bar.style.display='none'}
function pieces(t){t=t.replace(/\s+/g,' ').trim();var a=t.match(/[^。！？；.!?;]+[。！？；.!?;]?/g)||[t],out=[],b='';a.forEach(function(s){if((b+s).length>180){if(b)out.push(b);b=s}else b+=s});if(b)out.push(b);return out}
function say(text,l){stop();l=l||L();q=pieces(text);bar.querySelector('span').textContent=l==='en'?'Reading aloud…':'正在朗读…';bar.querySelector('button').textContent=l==='en'?'■ Stop':'■ 停止';bar.style.display='flex';var v=voice(l);
 (function nx(){if(!q.length){bar.style.display='none';return}var u=new SpeechSynthesisUtterance(q.shift());u.lang=l==='en'?'en-US':'zh-CN';if(v)u.voice=v;u.rate=l==='en'?1:1.05;u.onend=nx;u.onerror=function(){bar.style.display='none'};S.speak(u)})()}
window.tmSay=say;
function txt(el){var c=el.cloneNode(true);c.querySelectorAll('.say,script,style,.table-scroll,table,figure,.svg-scroll,pre,details,.tag,.term-foot').forEach(function(x){x.remove()});return c.textContent}
function btn(label){var b=document.createElement('button');b.type='button';b.className='say';b.innerHTML='<span class="zh" lang="zh-CN">🔊 '+label[0]+'</span><span class="en" lang="en">🔊 '+label[1]+'</span>';return b}
document.querySelectorAll('section.sec').forEach(function(sec){var h=sec.querySelector('h2');if(!h||sec.hasAttribute('data-glossary-skip'))return;var b=btn(['朗读要点','Read key points']);b.onclick=function(e){e.preventDefault();var t=h.textContent.replace(/🔊.*$/,'')+'。 ';var it=sec.querySelector(':scope>.intro');if(it)t+=txt(it);say(t,L())};h.appendChild(b)});
document.querySelectorAll('details.sub>.sub-body').forEach(function(bd){var b=btn(['朗读这一小节','Read this part']);b.onclick=function(){var s=bd.parentNode.querySelector('summary');say((s?s.textContent+'。 ':'')+txt(bd),L())};bd.insertBefore(b,bd.firstChild)});
document.querySelectorAll('article.term').forEach(function(a){var h=a.querySelector('.term-head');if(!h)return;var b=btn(['朗读','Read']);b.onclick=function(){say(txt(a),L())};h.appendChild(b)});
document.addEventListener('keydown',function(e){if(e.key==='Escape')stop()});addEventListener('pagehide',stop);
if(S.onvoiceschanged!==undefined)S.onvoiceschanged=function(){};})();