"""Generate the concise bilingual university-course comparison."""
import html
from pathlib import Path

ROOT = Path(__file__).resolve().parent
E = lambda value: html.escape(str(value), quote=True)

def t(zh, en, tag='span', cls=''):
    return f'<{tag} class="{cls}" data-zh="{E(zh)}" data-en="{E(en)}">{E(zh)}</{tag}>'

def a(url, zh, en, cls=''):
    extra = ' target="_blank" rel="noopener noreferrer"' if url.startswith('https://') else ''
    return f'<a href="{E(url)}" class="{cls}"{extra}>{t(zh,en)}</a>'

def cell(pair, secondary=None, cls=''):
    return '<td>'+t(*pair,'div',cls)+(t(*secondary,'div','secondary') if secondary else '')+'</td>'

# School, delivery, workload, price and credentials were rechecked September 7, 2026.
courses = [
 dict(id='yale-intro',rank=1,school=('耶鲁大学','Yale University'),unit=('心理学系 · Coursera','Psychology · Coursera'),title=('心理学导论','Introduction to Psychology'),topic=('情绪、决策、学习、社会行为','Emotion, decisions, learning, social behavior'),start=('现在可注册','Enroll now'),format=('自定进度，无直播','Self-paced; no live timetable'),hours=('约15–20小时','About 15–20 hours'),pace=('Yale：6周结构','Yale: six-week structure'),price='$49',fee=('官网参考价；地区可变','Official reference; region-dependent'),cert=('有 · 付费后通过测评','Yes · Paid track + assessments'),issuer=('Coursera 签发／Yale 标识','Coursera-issued / Yale branding'),age=('13+平台规则*','13+ platform rule*'),req=('无先修要求','No prerequisites'),official='https://online.yale.edu/courses/introduction-psychology',enroll='https://www.coursera.org/learn/introduction-psychology'),
 dict(id='harvard-rhetoric',rank=2,school=('哈佛大学','Harvard University'),unit=('文理学院 · HarvardX／edX','Arts & Sciences · HarvardX / edX'),title=('修辞：说服写作与演讲','Rhetoric: The Art of Persuasive Writing and Public Speaking'),topic=('说服技巧、论证、演讲分析与写作','Persuasion, arguments, speech analysis, writing'),start=('随时开始','Start anytime'),format=('On demand，无直播','On demand; no live meetings'),hours=('8周 × 每周2–3小时','8 weeks × 2–3 hours/week'),pace=('总计约16–24小时','About 16–24 hours total'),price='$209',fee=('证书价；可免费旁听','Certificate fee; free audit available'),cert=('有 · 认证课程证书','Yes · Verified course certificate'),issuer=('HarvardX／edX','HarvardX / edX'),age=('13+平台规则*','13+ platform rule*'),req=('需英语阅读与写作','English reading & writing'),official='https://harvardonline.harvard.edu/course/rhetoric-art-persuasive-writing-public-speaking',enroll='https://www.edx.org/learn/rhetoric/harvard-university-rhetoric-the-art-of-persuasive-writing-and-public-speaking'),
 dict(id='yale-negotiation',rank=3,school=('耶鲁大学','Yale University'),unit=('管理学院 · Coursera','School of Management · Coursera'),title=('谈判心理学','The Psychology of Negotiation: How to Find Elegant Trades'),topic=('理解需求、设计交换方案、谈判练习','Interests, trade-offs, negotiation practice'),start=('现在可注册','Enroll now'),format=('自定进度，无直播','Self-paced; no live timetable'),hours=('约6–9小时','About 6–9 hours'),pace=('Yale：4周结构','Yale: four-week structure'),price='$49',fee=('官网参考价；地区可变','Official reference; region-dependent'),cert=('有 · 付费后通过测评','Yes · Paid track + assessments'),issuer=('Coursera 签发／Yale 标识','Coursera-issued / Yale branding'),age=('13+平台规则*','13+ platform rule*'),req=('无先修；商业案例','No prerequisites; business cases'),official='https://online.yale.edu/courses/psychology-negotiation-how-find-elegant-trades',enroll='https://www.coursera.org/learn/psychology-of-negotiation'),
 dict(id='harvard-critical-thinking',school=('哈佛大学','Harvard University'),unit=('文理学院 · HarvardX／edX','Arts & Sciences · HarvardX / edX'),title=('论证结构与功能：批判性思维导论','Structure and Function of Argument: Introduction to Critical Thinking'),topic=('推理、逻辑谬误、论证图；偏思维训练','Reasoning, fallacies, argument mapping; thinking skills'),start=('随时开始','Start anytime'),format=('On demand，无直播','On demand; no live meetings'),hours=('8周 × 每周2–3小时','8 weeks × 2–3 hours/week'),pace=('总计约16–24小时','About 16–24 hours total'),price='$209',fee=('证书价；可免费旁听','Certificate fee; free audit available'),cert=('有 · 认证课程证书','Yes · Verified course certificate'),issuer=('HarvardX／edX','HarvardX / edX'),age=('13+平台规则*','13+ platform rule*'),req=('英语；论证练习','English; argument exercises'),official='https://harvardonline.harvard.edu/course/structure-function-argument-introduction-critical-thinking-0',enroll='https://harvardonline.harvard.edu/course/structure-function-argument-introduction-critical-thinking-0'),
 dict(id='stanford-logic',school=('斯坦福大学','Stanford University'),unit=('Stanford Online · Coursera','Stanford Online · Coursera'),title=('逻辑导论','Introduction to Logic'),topic=('形式逻辑、符号推理；情绪心理涉及较少','Formal logic and symbolic reasoning; limited emotion coverage'),start=('当前可注册†','Currently open†'),format=('Coursera 自定进度','Self-paced on Coursera'),hours=('约50小时','About 50 hours'),pace=('平台：5周 × 每周10小时','Platform: 5 weeks × 10 hours/week'),price=None,fee=('公开页未列价；登录后确认','Public page omits the fee; sign in to confirm'),cert=('有 · Coursera 课程证书','Yes · Coursera course certificate'),issuer=('付费并完成规定测评','Paid track + required assessments'),age=('13+平台规则*','13+ platform rule*'),req=('需集合与高中代数基础','Sets and high-school algebra'),official='https://logic.stanford.edu/intrologic/homepage/index.html',enroll='https://www.coursera.org/learn/logic-introduction'),
 dict(id='harvard-happiness',school=('哈佛大学','Harvard University'),unit=('HBS／Kennedy School师资 · HarvardX','HBS / Kennedy School faculty · HarvardX'),title=('管理幸福','Managing Happiness'),topic=('情绪、习惯、关系；偏幸福感','Emotion, habits, relationships; well-being focus'),start=('随时开始','Start anytime'),format=('On demand，无直播','On demand; no live meetings'),hours=('6周 × 每周2–3小时','6 weeks × 2–3 hours/week'),pace=('总计约12–18小时','About 12–18 hours total'),price='$219',fee=('证书价；可免费旁听','Certificate fee; free audit available'),cert=('有 · 认证课程证书','Yes · Verified course certificate'),issuer=('HarvardX／edX，非HBS Online','HarvardX / edX, not HBS Online'),age=('13+平台规则*','13+ platform rule*'),req=('无先修要求','No prerequisites'),official='https://harvardonline.harvard.edu/course/managing-happiness',enroll='https://www.edx.org/learn/happiness/harvard-university-managing-happiness'),
 dict(id='harvard-resilience',school=('哈佛大学','Harvard University'),unit=('医学院师资 · HarvardX／edX','Medical School faculty · HarvardX / edX'),title=('建立个人韧性','Building Personal Resilience: Managing Anxiety and Mental Health'),topic=('思想、情绪与行为的联系；自我管理','Thought–emotion–behavior links; self-management'),start=('随时开始','Start anytime'),format=('On demand，无直播','On demand; no live meetings'),hours=('6周 × 每周1–2小时','6 weeks × 1–2 hours/week'),pace=('总计约6–12小时','About 6–12 hours total'),price='$219',fee=('证书价；可免费旁听','Certificate fee; free audit available'),cert=('有 · 认证课程证书','Yes · Verified course certificate'),issuer=('HarvardX／edX','HarvardX / edX'),age=('13+平台规则*','13+ platform rule*'),req=('英语；个人实践活动','English; personal practice'),official='https://harvardonline.harvard.edu/course/building-personal-resilience-managing-anxiety-mental-health',enroll='https://harvardonline.harvard.edu/course/building-personal-resilience-managing-anxiety-mental-health'),
 dict(id='yale-teens',school=('耶鲁大学','Yale University'),unit=('心理学系 · Coursera','Psychology · Coursera'),title=('青少年幸福科学','The Science of Well-Being for Teens'),topic=('青少年情绪、压力、习惯；非说服主课','Teen emotion, stress and habits; limited persuasion'),start=('现在可注册','Enroll now'),format=('自定进度，无直播','Self-paced; no live timetable'),hours=('6周结构','Six-week structure'),pace=('平台估算约10小时','Platform estimate: about 10 hours'),price='$49',fee=('参考证书价；有免费无证书路线','Reference certificate fee; free no-certificate route'),cert=('有 · 选择付费路线','Yes · On the paid track'),issuer=('Coursera 签发／Yale 标识','Coursera-issued / Yale branding'),age=('青少年课程，13+*','Teen course; 13+*'),req=('明确为青少年设计','Explicitly designed for teens'),official='https://online.yale.edu/courses/science-well-being-teens',enroll='https://www.coursera.org/learn/the-science-of-well-being-for-teens')
]

def table(headers,rows,cls='',caption=None):
    out='<div class="table-scroll" tabindex="0" role="region" aria-label="课程比较 / Course comparison"><table class="'+cls+'">'
    if caption:out+='<caption>'+t(*caption)+'</caption>'
    if cls=='comparison':out+='<colgroup><col class="col-course"><col class="col-topic"><col class="col-start"><col class="col-time"><col class="col-price"><col class="col-cert"><col class="col-age"></colgroup>'
    return out+'<thead><tr>'+''.join('<th scope="col">'+t(*h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join(rows)+'</tbody></table></div>'

rows=[]
for c in courses:
    row=f'<tr id="{c["id"]}"><th scope="row"><div class="school-line">'+t(*c['school'],'span','school')
    if c.get('rank'):row+=f'<span class="rank-tag">#{c["rank"]}</span>'
    row+='</div>'+t(*c['unit'],'div','provider')+t(*c['title'],'div','course-title')+'<div class="row-links">'+a(c['official'],'官网 ↗','Official ↗')+a(c['enroll'],'报名 ↗','Enroll ↗')+'</div></th>'
    row+=cell(c['topic'])+cell(c['start'],c['format'],'available')+cell(c['hours'],c['pace'])
    row+='<td>'+(f'<div class="price">{E(c["price"])}</div>' if c['price'] else t('结算页确认','Check checkout','div','price unknown'))+t(*c['fee'],'div','secondary')+'</td>'
    row+=cell(c['cert'],c['issuer'])+cell(c['age'],c['req'])+'</tr>'
    rows.append(row)

parts=['''<!doctype html><html lang="zh-CN" data-language="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow, noarchive, nosnippet, noimageindex"><meta name="referrer" content="no-referrer">
<meta name="description" content="Compare Harvard, Yale, Stanford and Cornell online courses for Amy: availability, fees, workload, eligibility, certificates and top three recommendations.">
<title>Amy 名校在线课程比较 · Time Memo</title><link rel="canonical" href="https://timememo.net/amy-psychology/"><link rel="stylesheet" href="style.css?v=20260907b"></head><body>
<a class="skip-link" href="#main">Skip to content / 跳到正文</a><header class="topbar"><a class="brand" href="/">TIME MEMO <span>/ AMY</span></a><div class="language" aria-label="Language / 语言"><button type="button" data-lang="zh" aria-pressed="true">中文</button><button type="button" data-lang="en" aria-pressed="false">English</button><button type="button" data-lang="both" aria-pressed="false">中英 / Both</button></div></header><main id="main">''']
parts+=['<div class="page-heading"><div>'+t('Amy 名校在线课程比较','Amy’s university online course comparison','h1')+t('13岁 · 优先现在开始 · 自定进度 · 有证书选项','Age 13 · Start now preferred · Self-paced · Certificate options','p','subtitle')+'</div>'+t('重新核查：2026.09.07','Rechecked: September 7, 2026','span','verified')+'</div>']
parts+=['<nav class="jump-nav" aria-label="页面章节 / Sections">'+a('#compare','现在可学','Study now')+a('#not-now','暂不符合','Other programs')+a('#recommendations','推荐 1 / 2 / 3','Top 1 / 2 / 3')+a('reference/','完整资料','Full references')+'</nav>']
parts+=['<section id="compare"><div class="section-head">'+t('现在优先比较这8门','Compare these eight first','h2')+t('横向滑动可看完整表格 →','Scroll horizontally for all columns →','span','scroll-hint')+'</div>']
parts+=[table([('学校／承办 · 课程','School / provider · Course'),('内容重点','Main focus'),('开始时间／上课方式','Start / format'),('时长／每周投入','Duration / weekly work'),('费用（美元）','Cost (USD)'),('Certificate','Certificate'),('13岁资格／先修','Age 13 / prerequisites')],rows,'comparison',('全部在线；费用优先列证书路线，周数为课程结构或学习估算','All online; fees prioritize the certificate track; week counts describe structure or estimated pace'))+'</section>']
parts+=['<div class="table-notes">'+t('* 13+为平台最低年龄；监护人仍需核对当地及课程条件。以上证书均为非学分课程证书。','* 13+ is a platform age floor; a parent should check local and course conditions. These certificates are noncredit.','p')+t('† Stanford 官网称 Coursera 版本按季度开设；当前页面可注册并自定进度，之后的开放情况以报名页为准。','† Stanford describes its Coursera offering as quarterly. Enrollment and self-paced study are currently available; future access depends on the active offering.','p')+t('Yale 的$49为官方参考价；地区、单课／订阅方式可能影响结算价。edX免费旁听无证书，认证须在当期截止前完成。','Yale’s $49 is an official reference; region and purchase/subscription options can change checkout prices. Free edX audits do not include certificates; verified tracks have deadlines.','p')+'</div>']

excluded=[
 ('stanford-psychology',('Stanford · 心理学专题暑期班','Stanford · Topics in Psychology'),('8–11年级；另核对出生日期','Grades 8–11; birth-date rules apply'),('2026暑期已结束；2027未确认','Summer 2026 ended; 2027 unconfirmed'),('$3,200＋$65申请费（2026）','$3,200 + $65 application (2026)'),('有项目结业证书；无学分','Program completion certificate; noncredit')),
 ('harvard-extension',('Harvard Extension · PSYC E-15','Harvard Extension · PSYC E-15'),('至少15岁；13岁不符合','Minimum 15; ineligible at 13'),('2027春季固定学期；非随到随学','Fixed Spring 2027 semester'),('$2,260学分／$1,660非学分','$2,260 credit / $1,660 noncredit'),('单课无结业证；有成绩单记录','No single-course certificate; transcript record')),
 ('hbs-negotiation',('HBS Online · Negotiation Mastery','HBS Online · Negotiation Mastery'),('18+；13岁不符合','18+; ineligible at 13'),('随时开始；90天完成','Start anytime; finish within 90 days'),('$1,949','$1,949'),('HBS Online 结业证书','HBS Online completion certificate')),
 ('cornell-precollege',('Cornell · 在线心理学学分课','Cornell · Online psychology for credit'),('15+且完成十年级','15+ and completed grade 10'),('按学期／暑期，非随到随学','Scheduled sessions; not on-demand'),('3学分$5,820＋$75申请费（2026）','3 credits: $5,820 + $75 application (2026)'),('大学学分与正式成绩单','Academic credit & official transcript')),
 ('ecornell-leadership',('eCornell · Psychology of Leadership','eCornell · Psychology of Leadership'),('18+；13岁不符合','18+; ineligible at 13'),('按期开课；3个月，每周4–6小时','Cohort starts; 3 months, 4–6 hours/week'),('$3,750','$3,750'),('Cornell 非学分专业证书','Cornell noncredit professional certificate'))
]
parts+=['<section id="not-now"><div class="section-head">'+t('这些名校项目，暂不符合本次条件','These programs do not meet the current criteria','h2')+'</div>']
erows=[]
for id,name,age,start,cost,cert in excluded:
    erows+=['<tr><th scope="row">'+a('reference/#'+id,*name)+'</th>'+cell(age)+cell(start)+cell(cost)+cell(cert)+'</tr>']
parts+=[table([('学校／项目','School / program'),('年龄条件','Age requirement'),('开始时间／时长','Start / duration'),('费用','Cost'),('证书／学分','Credential / credit')],erows,'alternatives',('点击项目名查看资格来源；旧年度价格已标明','Select a program for eligibility sources; older-cycle prices are labeled'))+'</section>']

parts+=['<section id="recommendations"><div class="section-head">'+t('最后怎么选：推荐 1 / 2 / 3','The decision: recommendations 1 / 2 / 3','h2')+'</div><ol class="recommendations">']
recs=[
 ('yale-intro','第一推荐','First choice','Yale · 心理学导论','Yale · Introduction to Psychology','最适合作为第一门：直接覆盖情绪、决策和行为，基础完整；约15–20小时，证书参考$49。','Best first course: emotion, decisions and behavior within a broad foundation. About 15–20 hours; reference certificate fee $49.'),
 ('harvard-rhetoric','第二推荐','Second choice','Harvard · 说服写作与演讲','Harvard · Rhetoric','如果更想学“怎样说服人”，或更看重哈佛品牌，可优先选它。8周结构，每周2–3小时，证书$209。','Choose this first if persuasion or the Harvard brand matters most. Eight-week structure, 2–3 hours/week; certificate $209.'),
 ('yale-negotiation','第三推荐','Third choice','Yale · 谈判心理学','Yale · Psychology of Negotiation','适合短课实践：理解对方需求、设计双方都能接受的方案。约6–9小时，证书参考$49。','A short practical course on interests and mutually acceptable trades. About 6–9 hours; reference certificate fee $49.')
]
for id,z,e,titlez,titlee,reasonz,reasone in recs:
    parts+=['<li><div class="rec-rank">'+t(z,e)+'</div><div><h3>'+a('#'+id,titlez,titlee)+'</h3>'+t(reasonz,reasone,'p')+'</div></li>']
parts+=['</ol><div class="decision-note">'+t('更看重推理训练：改选 Harvard 批判性思维导论。坚持 Stanford：可考虑逻辑导论，但它更偏数学／形式推理，对情绪与说服的覆盖较少。','For reasoning practice, choose Harvard’s Critical Thinking course. If Stanford is essential, consider Introduction to Logic, with its stronger mathematical/formal focus and limited emotion or persuasion coverage.','p')+'</div></section>']
parts+=['<details class="enrollment-note" id="register"><summary>'+t('报名只需核对这4件事','Four enrollment checks')+'</summary><ol>']
for z,e in [('从表格的官网／报名入口进入，确认学校、课程名及当前可用批次。','Follow Official/Enroll and verify the school, course and active offering.'),('核对13+平台条件，以 Amy 真实信息注册，监护人协助付款。','Check platform eligibility; register with Amy’s accurate information, with parental payment help.'),('选择免费学习或付费证书；付款前确认单课价／订阅价、续费及截止日期。','Choose free learning or certification; confirm course/subscription charges, renewal and deadlines.'),('完成课内规定的作业与及格要求后领取证书。','Complete required assessments and passing criteria to receive the certificate.')]:parts+=[t(z,e,'li')]
parts+=['</ol><div class="policy-links">'+a('https://www.coursera.org/about/terms','Coursera 年龄与条款','Coursera eligibility & terms')+a('https://support.edx.org/hc/en-us/articles/13481901497239-Can-anyone-use-edX','edX 年龄规则','edX age policy')+'</div></details>']
parts+=['<footer>'+a('reference/','完整资料：各课细则、Harvard 注册及原调研 →','Full references: course details, Harvard registration & earlier research →')+'<button type="button" class="print-button" id="print-guide">'+t('打印比较表','Print comparison')+'</button></footer></main><script src="app.js?v=20260907b"></script></body></html>']
(ROOT/'index.html').write_text('\n'.join(parts),encoding='utf-8')
print('Generated comparison: 8 current courses, 5 other programs, 3 ranked recommendations.')
