import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
data = json.loads((ROOT / 'content.json').read_text())
courses = data['courses']
by_id = {c['id']: c for c in courses}
E = lambda x: html.escape(str(x), quote=True)

def t(zh, en, tag='span', attrs=''):
    return f'<{tag} data-zh="{E(zh)}" data-en="{E(en)}" {attrs}>{E(zh)}</{tag}>'

def p(zh, en, cls=''):
    return t(zh, en, 'p', f'class="{cls}"' if cls else '')

def link(url, zh, en, cls=''):
    external = ' target="_blank" rel="noopener noreferrer"' if url.startswith('https://') else ''
    return t(zh, en, 'a', f'href="{E(url)}" class="{cls}"{external}')

def source(url, zh, en):
    return '<p class="source">' + link(url, zh, en) + '</p>'

def section(id, num, zh, en, desc=None):
    s = f'<section class="guide-section" id="{id}"><div class="section-heading"><span class="section-number">{num}</span>' + t(zh,en,'h2') + '</div>'
    return s + (p(*desc, cls='section-intro') if desc else '')

def list_items(items, ordered=False):
    tag='ol' if ordered else 'ul'
    return f'<{tag}>' + ''.join(t(*x,'li') for x in items) + f'</{tag}>'

def details(zh,en,body,opened=False):
    return '<details class="note-details"'+(' open' if opened else '')+'><summary>'+t(zh,en)+'</summary><div class="details-inner">'+body+'</div></details>'

def table(headers, rows, caption):
    return '<div class="table-scroll" tabindex="0" role="region" aria-label="Course comparison / 课程比较"><table><caption>'+t(*caption)+'</caption><thead><tr>'+''.join('<th scope="col">'+t(*h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<'+('th scope="row"' if j==0 else 'td')+'>'+cell+'</'+('th' if j==0 else 'td')+'>' for j,cell in enumerate(row))+'</tr>' for row in rows)+'</tbody></table></div>'

parts = ['''<!doctype html>
<html lang="zh-CN" data-language="zh">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow, noarchive, nosnippet, noimageindex"><meta name="referrer" content="no-referrer">
<meta name="description" content="A bilingual course guide for Amy: emotion, reasoning, decision-making and persuasion. Harvard, Yale, Stanford, Cornell, Wesleyan and APA courses, age rules, fees and certificates.">
<title>Amy 的心理学选课指南 · Time Memo</title>
<link rel="canonical" href="https://timememo.net/amy-psychology/">
<link rel="stylesheet" href="style.css">
</head><body>
<a class="skip-link" href="#main">Skip to content / 跳到正文</a>
<header class="topbar"><a href="/" class="brand">TIME MEMO <span>/ AMY LEARNS</span></a><div class="language" aria-label="Language / 语言"><button type="button" data-lang="zh" aria-pressed="true">中文</button><button type="button" data-lang="en" aria-pressed="false">English</button><button type="button" data-lang="both" aria-pressed="false">中英 / Both</button></div></header>
<main id="main">
''']
parts += [p('13岁 · 八年级 · 在线心理学选课','Age 13 · Grade 8 · Online psychology courses','eyebrow'),t('人，为什么这样选择？','Why do people choose what they choose?','h1'),p('情绪如何影响判断？人为什么改变主意？为 Amy 寻找关于推理、决策与说服的课程。','How does emotion shape judgment? Why do people change their minds? A course guide to reasoning, decisions and persuasion for Amy.','lede')]
parts += ['<div class="metadata">'+t('核查于2026年9月7日','Verified September 7, 2026')+t('价格均为美元 · 上课时间注明时区','Prices in USD · Time zones stated')+'</div>']
parts += ['<section class="recommendation" aria-labelledby="recommendation-title">'+p('给 Amy 的选课结论','The recommendation for Amy','eyebrow')+t('重点找“判断与决策”和“社会心理学”。','Look for judgment & decision-making and social psychology.','h2','id="recommendation-title"')+p('“推理心理学”抓住了她的一部分兴趣。加上情绪、动机和社会影响，才能更完整地回答她想问的问题。下面的排序是按兴趣契合度作出的建议。','Psychology of reasoning captures part of her interest. Emotion, motivation and social influence complete the picture. The recommendations below reflect subject fit.')+'</section>']

shorts=[('apa-decisions','01','主题最贴近','Closest topic match','APA · Decision Making','约10小时，把情绪、动机、偏差和说服连起来。适合先试学。','About 10 hours connecting emotion, motivation, biases and persuasion. A focused first sample.'),('wesleyan-social','02','大学课程首选','University course pick','Wesleyan · Social Psychology','深入研究判断、态度改变和群体影响。约40小时，适合慢慢学。','Explore judgment, attitude change and group influence. About 40 hours, best spread over time.'),('yale-intro','03','先建立完整基础','Build a broad foundation','Yale · Intro to Psychology','覆盖心理学全貌。约15–20小时，适合还没系统学过心理学的 Amy。','A map of psychology in about 15–20 hours, useful before specializing.')]
parts.append('<div class="shortlist">')
for id,n,zh,en,title,desczh,descen in shorts:
    parts.append('<article><span class="number">'+n+' / '+t(zh,en)+'</span><h3>'+E(title)+'</h3>'+p(desczh,descen)+link('#'+id,'查看年龄、费用与证书 →','Age, fees & certificate →')+'</article>')
parts.append('</div>')
parts.append(p('APA 是美国心理学会，单独标为非大学选项。Coursera／edX 的“13+”是平台最低年龄，不代表青少年专班或校方已批准 Amy 的个人资格。','APA is the American Psychological Association and is labeled separately from universities. “13+” on Coursera/edX is a platform age floor, not a teen cohort or individual admission approval.','small-note'))

nav=[('fit','兴趣方向','Subject fit'),('compare','快速比较','Compare'),('courses','全部课程','All courses'),('register','报名步骤','Enrollment'),('harvard-details','哈佛完整说明','Harvard details'),('plan','学习路线','Learning path'),('credentials','证书与来源','Credentials & sources')]
parts.append('<nav class="jump-nav" aria-label="Guide sections / 章节">'+''.join(link('#'+i,zh,en) for i,zh,en in nav)+'</nav>')

parts.append(section('fit','01','比“推理心理学”更完整的方向','A fuller fit than reasoning alone'))
parts.append('<div class="question-map">')
topics=[('为什么推导出这个结论？','Why draw this conclusion?','推理心理学／认知心理学','Psychology of reasoning / cognitive psychology','研究推断、证据、问题解决与思维错误。','Inference, evidence, problem-solving and errors in thinking.'),('为什么明知有道理，还做了别的选择？','Why choose differently despite a logical argument?','判断与决策／情绪与动机','Judgment & decision-making / emotion & motivation','最贴近 Amy 的核心问题：目标、感受与认知偏差怎样改变选择。','The core fit: how goals, feelings and cognitive biases affect choices.'),('为什么有人容易被说服，有人不会？','Why are some people more persuadable?','社会心理学／社会影响','Social psychology / social influence','研究态度、群体规范、关系、说服及情境因素。','Attitudes, group norms, relationships, persuasion and context.'),('怎样更好地表达并达成共识？','How can I communicate and reach agreement?','谈判／有原则的说服','Negotiation / principled persuasion','练习理解利益、说明理由、比较方案；也学习识别操控性沟通。','Practice understanding interests, giving reasons and comparing options; also learn to recognize manipulative communication.')]
for a,b,c,d,e,f in topics:
    parts.append('<article>'+t(a,b,'h3')+p(c,d,'field-name')+p(e,f)+'</article>')
parts.append('</div><div class="reading-note">'+t('先回答 Amy 的问题','A starting answer for Amy','h3')+p('情绪和逻辑会共同参与选择。情绪帮助我们给结果赋予价值，也可能把与当前决定无关的感受带进判断。因此不能简单地把人分为“情绪型”和“逻辑型”；情绪既可能改善决定，也可能造成偏差。','Emotion and reasoning work together in choices. Feelings help assign value to outcomes, and unrelated feelings can also spill into judgment. People cannot be neatly divided into emotional and logical types; emotion can improve decisions or bias them.')+p('看到两个人做出不同选择，可以分别问：他们知道什么、在乎什么、处于什么情境、受到谁的影响？下面课程覆盖这些机制。学说服时，把练习目标放在清楚表达、理解对方和允许对方自主选择。','When two people choose differently, ask what each knows, values, experiences and hears from others. The courses below examine these mechanisms. For persuasion practice, aim for clear communication, understanding and room for the other person to choose.')+source('https://www.annualreviews.org/content/journals/10.1146/annurev-psych-010213-115043','研究依据：Lerner 等，Emotion and Decision Making（2015）','Research: Lerner et al., Emotion and Decision Making (2015)')+source('https://www.annualreviews.org/content/journals/10.1146/annurev-neuro-071013-014119','补充研究：Phelps 等，情绪与决策的相互调节（2014）','Further research: Phelps et al., emotion–decision interactions (2014)')+'</div></section>')

parts.append(section('compare','02','先比较最值得看的七个选择','Seven options worth comparing',('都可在线学习。自定进度课程的“几周完成”是估算；直播项目有固定出勤要求。','All are online. Week counts for self-paced courses are estimates; live programs require attendance.')))
compare=[('apa-decisions','APA · Decision Making','13+平台','13+ platform','约10小时','About 10 hours','付费课程证书','Paid course certificate','结算时确认','Check checkout'),('wesleyan-social','Wesleyan · Social Psychology','13+平台','13+ platform','约40小时','About 40 hours','付费课程证书','Paid course certificate','结算时确认','Check checkout'),('yale-intro','Yale · Intro to Psychology','13+平台','13+ platform','约15–20小时','About 15–20 hours','Coursera／Yale','Coursera / Yale','$49参考价','$49 reference'),('yale-negotiation','Yale · Psychology of Negotiation','13+平台','13+ platform','约6–9小时','About 6–9 hours','Coursera／Yale','Coursera / Yale','$49参考价','$49 reference'),('yale-teens','Yale · Well-Being for Teens','青少年课程，13+平台','Teen course; 13+ platform','6周结构','Six-week structure','免费无证／付费有证','Free no-cert / paid cert','$49参考价','$49 reference'),('stanford-psychology','Stanford · Topics in Psychology','8–11年级，另核对年龄','Grades 8–11; age rules apply','2周密集直播','Two intensive live weeks','项目结业证书','Program completion certificate','$3,200（2026已结束）','$3,200 (2026 ended)'),('harvard-happiness','HarvardX · Managing Happiness','13+平台','13+ platform','6周×2–3小时','Six weeks × 2–3 hours','HarvardX／edX','HarvardX / edX','$219','$219')]
rows=[]
for id,title,az,ae,tz,te,cz,ce,pz,pe in compare:
    rows.append([f'<a href="#{id}">{E(title)}</a>',t(az,ae),t(tz,te),t(cz,ce),t(pz,pe)])
parts.append(table([('课程','Course'),('年龄／人群','Age / audience'),('时间投入','Time'),('证书路线','Certificate route'),('费用','Fee')],rows,('点击课程名称查看来源和完整要求','Select a course name for sources and full requirements')))
parts.append('<div class="future-strip">'+t('现在不符合年龄的路径','Paths with higher age requirements','h3')+p('Harvard Extension 本科／非学分至少15岁；Cornell 在线 Precollege 至少15岁且完成十年级；HBS Online、eCornell 和所列 Harvard 盲点课程要求18+。完整说明保留在下方，方便以后规划。','Harvard Extension undergraduate/noncredit study starts at 15; Cornell online Precollege requires 15+ and completed grade 10; HBS Online, eCornell and the listed Harvard blind-spots course require 18+. Details remain below for future planning.')+'</div></section>')

parts.append(section('courses','03','全部课程与官方入口','Course details & official enrollment links',(f'共{len(courses)}条课程／项目路径。展开卡片查看年龄、课时、费用、证书与要求；所有评估建议均以 Amy 当前兴趣为出发点。',f'{len(courses)} course/program paths. Expand each entry for age, schedule, fees, credentials and requirements. Recommendations reflect Amy’s current interests.')))
groups=[('recommended','现在优先比较','Compare first'),('teen','专门面向青少年的直播项目','Live enrichment for teenagers'),('harvard','HarvardX：保留此前查到的选项','HarvardX: options from the earlier research'),('future','以后再考虑：学期课与成人证书','For later: semester courses & adult certificates'),('free','先试看：免费公开课程','Sample first: free open lectures')]
fields=[('age','13岁是否适用','Age 13 eligibility'),('time','上课时间与投入','Schedule & workload'),('price','费用','Cost'),('credential','证书与学分','Credential & credit'),('requirements','学习与完成要求','Study & completion requirements')]
for group,zh,en in groups:
    parts.append(t(zh,en,'h3',f'class="group-title" id="group-{group}"')+'<div class="course-grid">')
    for c in [c for c in courses if c['group']==group]:
        parts.append(f'<details class="course" id="{c["id"]}" data-course="{c["id"]}"><summary><span class="course-school">'+E(c['school'])+'</span>'+t(*c['title'],'span','class="course-name"')+'<span class="course-original" lang="en">'+E(c['title'][1])+'</span>'+t(*c['tag'],'span','class="tag '+('tag-future' if group=='future' else 'tag-teen' if group=='teen' else '')+'"')+'</summary><div class="course-body">'+p(*c['fit'],'course-fit')+'<dl>')
        for key,z,e in fields:
            parts.append('<div>'+t(z,e,'dt')+t(*c[key],'dd')+'</div>')
        parts.append('</dl><div class="course-links">'+''.join(link(u,z+' ↗',e+' ↗') for z,e,u in c['links'])+'</div></div></details>')
    parts.append('</div>')
parts.append('</section>')

parts.append(section('register','04','怎样报名、怎样上课、怎样拿证','Enroll, study and earn the certificate'))
parts.append('<div class="enrollment-grid"><article class="enrollment"><span class="number">A / COURSERA</span>'+t('Yale、Wesleyan 与 APA','Yale, Wesleyan & APA','h3'))
parts.append(list_items([('从上面的官方链接进入，确认课程提供者和教师。Yale 导论的正确地址结尾是 introduction-psychology。','Use the official links above and confirm the provider and instructor. The Yale introduction’s correct URL ends in introduction-psychology.'),('核对平台年龄与地区条件，以 Amy 的真实姓名和信息创建她的学习账户。监护人协助核对条款与付款。','Check age and regional requirements; use Amy’s accurate name and information for her learner account. A parent can help review terms and payment.'),('查看可用的预览、免费无证书、单课证书或订阅选项。若选试用，核对转付费日期与取消方式。','Review available preview, free/no-certificate, individual certificate or subscription options. For a trial, check conversion and cancellation terms.'),('进入课程后查看 Grades／课程要求，确认必做作业、同伴互评、及格分数及截止日期。','Inside the course, check Grades and requirements for mandatory work, peer reviews, passing scores and deadlines.'),('按自己的节奏看录像、阅读、做题；通过全部要求后，到 Accomplishments 查看、下载或分享电子证书。','Watch, read and complete assessments at a suitable pace. After fulfilling all requirements, access the digital certificate in Accomplishments.')],True))
parts.append(p('年龄核实的边界：13岁达到了平台最低年龄，但 Coursera 还规定合同能力、当地数据同意年龄及课程条件。监护人需核对这些条件；这里没有把最低年龄当成个人资格已获确认。','Age eligibility: 13 meets the platform floor, but Coursera also requires contractual capacity, local data-consent eligibility and course-specific compliance. A parent should check these conditions; the age floor alone is not individual eligibility confirmation.','small-note'))
parts.append(source('https://www.coursera.org/about/terms','Coursera 条款：年龄、账户与非学分性质','Coursera terms: age, accounts and noncredit study')+'</article>')
parts.append('<article class="enrollment"><span class="number">B / HARVARDX · EDX</span>'+t('先旁听，再决定是否买证书','Audit first, then decide on certification','h3'))
parts.append(list_items([('核对13+平台年龄条件；在 edX 使用 Amy 的真实学习者信息。','Check edX’s 13+ age requirement and use Amy’s accurate learner information.'),('从 Harvard 官方课程页进入 edX。免费 Audit 的访问通常有限时，且不含认证测评或证书。','Follow Harvard’s course link to edX. Free audit access is generally time-limited and excludes certificate assessments and certification.'),('如需要证书，在 Important Dates 列出的升级截止前购买 Verified 路线；不要等到课程结束才决定。','For certification, buy the verified track before the upgrade deadline in Important Dates; do not wait until the course ends.'),('完成所有必做活动并达到课内及格标准。身份或姓名验证按账户实际提示办理，不假定所有课程都要求同一种证件。','Complete required activities and the in-course passing threshold. Follow any identity/name checks actually requested by the account.'),('达到认证要求后保存电子证书和验证链接。组合项目还须完成全部组成课程。','Save the electronic certificate and verification link after meeting requirements. Program bundles require all component courses.')],True))
parts.append(p('批次提醒：核查 Managing Happiness 时，免费旁听访问显示至10月20日、课程结束10月21日。每个账户的访问和升级日期应以登录后的页面为准。','Run-specific note: Managing Happiness showed audit access through October 20 and course end October 21 when checked. Use the dates shown in the learner’s account for access and upgrading.','small-note'))
parts.append('<div class="course-links">'+link('https://support.edx.org/hc/en-us/articles/13481901497239-Can-anyone-use-edX','年龄要求','Age requirements')+link('https://support.edx.org/hc/en-us/articles/206211958-What-does-it-cost-to-take-a-course','旁听与付费区别','Audit versus paid study')+link('https://support.edx.org/hc/en-us/articles/207204437-What-is-the-deadline-to-upgrade-to-a-verified-certificate','升级截止规则','Upgrade deadlines')+'</div></article></div>')
parts.append(details('Stanford 下一期：申请而非即时购买','Next Stanford cycle: an application, not instant enrollment',list_items([('等待官网公布下一年课程与规则，再按出生日期、申请时年级和课程范围核对资格。','Wait for the next catalog and policies, then check date of birth, grade at application and course restrictions.'),('未成年学生与监护人共同提交申请；准备指定学期的学业记录、申请费及当年要求的补充材料。','A minor and parent/guardian submit together; prepare the requested academic records, application fee and any cycle-specific materials.'),('最多排序3门志愿；录取后确认一门课程、付款并完成入学文件。','Rank up to three preferences; if admitted, accept one course, pay and complete enrollment documents.'),('暑期留出连续两周的直播和作业时间；按出勤、参与和完成要求取得结业证书。','Reserve two consecutive weeks for live meetings and homework; satisfy attendance, participation and completion requirements.')],True)+source('https://summerinstitutes.spcs.stanford.edu/admissions','Stanford 官方申请流程','Official Stanford application process')))
parts.append('</section>')

parts.append(section('harvard-details','05','之前的 Harvard 研究，完整保留','The earlier Harvard research, retained in detail',('原来推荐的幸福课程现在列为补充。Amy 新提出的情绪、推理和说服兴趣，决定了本页新的选课顺序。','Happiness courses are now supplementary. Amy’s clarified interest in emotion, reasoning and persuasion drives the updated recommendations.')))
body=p('Harvard College 的基础课程称 PSY 1：Introduction to Psychological Science，属于本科课程体系。面向公众的学期注册路线是 Harvard Extension School 的 PSYC E-15。HarvardX、Harvard Online 和 HBS Online 的年龄及证书规则各不相同。','Harvard College’s foundation course is PSY 1: Introduction to Psychological Science, within the undergraduate curriculum. The public semester-enrollment route is Extension School’s PSYC E-15. HarvardX, Harvard Online and HBS Online have different eligibility and credential rules.')+source('https://undergrad.psychology.fas.harvard.edu/introductory-course','Harvard Psychology：本科入门课说明','Harvard Psychology: undergraduate introductory course')
parts.append(details('“Harvard Psychology 101”究竟是哪一条路线？','Which route does “Harvard Psychology 101” mean?',body))

calrows=[('2026秋季授课','Fall 2026 classes','2026-08-31 → 2026-12-19'),('2026秋季新生注册截止（已过）','Fall 2026 new registration deadline (passed)','2026-08-24'),('已注册学生调整课程窗口','Course changes for already registered students','2026-08-25 → 2026-09-08'),('2027春季开放注册','Spring 2027 registration','2026-11-05 → 2027-01-19'),('春季付款截止','Spring payment deadline','2027-01-07'),('春季英语材料截止','Spring English evidence deadline','2027-01-12'),('2027春季授课','Spring 2027 classes','2027-01-25 → 2027-05-15')]
body=table([('事项','Milestone'),('日期','Date')],[[t(z,e),E(date)] for z,e,date in calrows],('Harvard Extension 校历；不改变13岁不符合资格的结论','Harvard Extension calendar; age 13 remains ineligible'))+p('1月7日后注册须立即付款。秋季目录标为 Open，不表示新学生可以绕过8月24日截止；9月8日的课程调整窗口仅适用于已注册学生。','Registration after January 7 requires immediate payment. An “Open” fall listing does not override the August 24 deadline; the September 8 change window is for already registered students.')+source('https://extension.harvard.edu/registration-admissions/academic-calendar/','官方校历与截止时间','Official calendar & deadlines')
body += p('Course Browser 的部分横幅年份与列表日期显示不一致；这里的学期和注册日期采用 Extension 官方校历。报名时以 MyDCE 最终确认的信息为准。','Some Course Browser banner years and listing dates are inconsistent. Semester and registration dates here follow the official Extension calendar; verify final details in MyDCE at registration.','small-note')
parts.append(details('PSYC E-15：学期与注册日期','PSYC E-15: semester and registration dates',body))

body=list_items([('先核对年龄、英语及课程条件；未满15岁不能注册本科或非学分课程。','First verify age, English and course conditions; under-15s cannot enroll for undergraduate or noncredit study.'),('建立 MyDCE／DCEKey 账户，完成当学期的预注册信息。','Create a MyDCE/DCEKey account and complete term preregistration.'),('查找 PSYC E-15；2027春季 CRN 23862，2026秋季 CRN 10232。','Find PSYC E-15; Spring 2027 CRN 23862, Fall 2026 CRN 10232.'),('选择本科或非学分选项，加入选课车，再提交正式注册；仅加购物车不等于注册成功。','Choose undergraduate or noncredit study, add the course, then submit registration; adding to a cart alone is insufficient.'),('按截止时间付款，核对注册确认，领取／设置 HarvardKey，再进入 Canvas 与 Zoom。','Pay by the deadline, verify registration confirmation, claim/set up HarvardKey, then access Canvas and Zoom.')],True)+p('单门公开课程一般不需要学位入学申请，但仍必须满足注册资格。进一步核实可联系 Enrollment Services：info@dce.harvard.edu，+1 617-495-4024。','Public individual courses generally do not require a degree-admission application, but enrollment requirements still apply. Eligibility contact: Enrollment Services, info@dce.harvard.edu, +1 617-495-4024.')+source('https://extension.harvard.edu/registration-admissions/course-registration/','MyDCE 官方注册步骤','Official MyDCE registration steps')
parts.append(details('PSYC E-15：注册操作流程','PSYC E-15: registration workflow',body))

body=p('2027春季周四5:30–7:30pm美东，对应洛杉矶2:30–4:30pm。课程允许按规定选择 Zoom 直播或录像；录像通常在当天或下一个工作日提供。异步不等于没有每周截止。','Spring 2027 meetings are Thursdays 5:30–7:30pm Eastern, or 2:30–4:30pm Los Angeles. The course permits Zoom or recordings under its rules; recordings are generally available the same or next business day. Asynchronous study still has weekly deadlines.')+p('直播需要稳定网络、电脑、摄像头和麦克风；不适合在途中用手机参加。Extension 建议每1小时课堂至少预留2小时课外学习，因此可先按每周6小时以上规划，实际以作业量为准。','Live participation requires stable internet, a computer, camera and microphone; joining by phone while traveling is unsuitable. Extension suggests at least two outside study hours per class hour, so allow at least six hours/week initially and adjust to the workload.')+source('https://coursebrowser.dce.harvard.edu/course/introduction-to-psychology-3/','春季课程形式与时间','Spring format & schedule')+source('https://extension.harvard.edu/about/faq/','Extension 学习投入 FAQ','Extension workload FAQ')
parts.append(details('PSYC E-15：直播、录像、时区与设备','PSYC E-15: live class, recordings, time zones & equipment',body))

graderows=[('数据项目1','Data project 1','20%','2026-09-24'),('期中考试','Midterm','15%','2026-10-15'),('数据项目2','Data project 2','20%','2026-11-12'),('6次作业合计','Six homework assignments combined','10%',t('按课内安排','In-course schedule')),('期末考试','Final exam','35%','2026-12-17')]
body=p('以下来自2026秋季公开 syllabus，作为工作量示例，不能把这些作业日期直接套用到2027春季。','The following comes from the public Fall 2026 syllabus as a workload example. These assignment dates do not apply automatically to Spring 2027.')+table([('评估','Assessment'),('比重','Weight'),('日期','Date')],[[t(z,e),weight,date] for z,e,weight,date in graderows],('2026秋季评分结构','Fall 2026 grading structure'))+p('秋季期中是90分钟开卷、可用笔记，须在10月15日00:01–23:59美东的窗口内完成。看录像者应在下次直播前跟上内容与作业；不记录出勤不代表没有学习责任。','The fall midterm is a 90-minute open-book/open-note exam within the October 15, 00:01–23:59 Eastern window. Recording viewers should catch up before the next live class; unrecorded attendance does not remove learning responsibilities.')+p('非学分学生可以听课和讨论，但不提交作业、论文或考试，不评分。因此，如果目标是批改反馈或正式成绩，应先理解两种注册选项的区别。','Noncredit students may attend and discuss but do not submit homework, papers or exams and receive no grade. Consider that distinction when seeking assessed work or formal grades.')+source('https://harvard.simplesyllabus.com/en-US/doc/zd5mwcoob','PSYC E-15：2026秋季公开 syllabus','PSYC E-15: public Fall 2026 syllabus')
parts.append(details('PSYC E-15：作业、考试与非学分限制','PSYC E-15: assignments, exams & noncredit limitations',body))

body=p('英语为母语者无需提交英语能力证明；学校将母语定义为最先学会读、写、理解和说的语言。其他学生可提交合格成绩单或考试成绩。仅在英语学校就读不一定自动豁免。','Native English speakers need no proficiency evidence; Harvard defines native language as the first learned for reading, writing, understanding and speaking. Others may use qualifying transcripts or test scores. Attendance at an English-medium school alone does not automatically establish an exemption.')+p('成绩单路线需要已获得高中毕业文凭或大学学位，并显示在授予该资格、以英语教学的学校至少学习一年；在读、尚未授予的资格不接受。考试成绩须在两年内且可验证。','The transcript route requires an awarded high-school diploma or university degree, plus at least one year at the awarding English-medium institution. In-progress qualifications are insufficient. Test scores must be verifiable and no more than two years old.')+table([('考试','Test'),('最低要求','Minimum')],[[E('TOEFL iBT'),t('新制5.0/6；或旧制100/120','New scale 5.0/6; or legacy 100/120')],[E('IELTS Academic'),'7.0'],[E('PTE Academic'),'70'],[E('Duolingo English Test'),'125']],('Extension 英语成绩要求','Extension English test requirements'))+p('通过 MyDCE 的 Document Uploader 上传材料并查看审核状态；2027春季材料截止1月12日，尽量在注册开始前完成。','Upload evidence through MyDCE’s Document Uploader and check approval status. The Spring 2027 deadline is January 12; aim to complete this before registration opens.')+source('https://extension.harvard.edu/registration-admissions/course-registration/english-proficiency-requirement/','完整英语政策、豁免与上传说明','Full English policy, exemptions & upload instructions')
parts.append(details('PSYC E-15：英语要求与材料','PSYC E-15: English proficiency & documentation',body))

body=p('普通 HBS Online Certificate Courses 当前无需提交传统入学申请，通常是建立账户、选择开课期、填写注册信息并付款；但18+和英语要求仍适用。Credential Programs 的申请流程可能不同。','Ordinary HBS Online Certificate Courses currently use account creation, course/date selection, enrollment details and payment rather than a traditional application. The 18+ and English requirements still apply. Credential Programs may use a different application process.')+p('“Harvard 教授授课”“使用 HBS 平台”“HarvardX 证书”和“HBS Online 签发”是不同事实。上方课程卡分别注明提供单位和证书性质。','A Harvard instructor, the HBS learning platform, a HarvardX certificate and an HBS Online-issued credential describe different facts. Each course above identifies its provider and credential.')+source('https://online.hbs.edu/help/faqs/enrollment','HBS Online 注册 FAQ','HBS Online enrollment FAQ')+source('https://online.hbs.edu/legal/terms-of-use','HBS Online 使用条款','HBS Online terms')
parts.append(details('HBS Online：怎样注册、谁签发证书','HBS Online: enrollment and certificate issuer',body))
parts.append('</section>')

parts.append(section('plan','06','Amy 可以怎样开始','A practical start for Amy',('这是建议节奏，不是学校规定，也不需要同时报名全部课程。','This is a suggested pace, not a school requirement; there is no need to enroll in everything.')))
parts.append('<div class="path">')
stages=[('01','先用一周判断兴趣','Use a week to check the fit','观看 APA 决策课或 Wesleyan 社会心理学的可用预览；若希望先有全貌，试 Yale 导论。记录最想继续追问的3个问题。','Try an available preview from APA’s decision course or Wesleyan’s social psychology. For a broader map, try Yale’s introduction. Write three questions worth pursuing.'),('02','完成一门主课','Complete one main course','偏向情绪与偏差：先做 APA，约3–4周。偏向人际影响：选 Wesleyan，约8–10周。若选 Yale 基础课，可按6–8周学习。','For emotion and bias, start with APA over 3–4 weeks. For social influence, choose Wesleyan over 8–10 weeks. Yale’s foundation can be spread over 6–8 weeks.'),('03','再练习实际沟通','Then practice communication','选择 Yale 谈判心理学作为短课补充。以家庭活动、社团项目或时间分配为例，练习说明需求、询问对方重点和提出双方都能接受的方案。','Use Yale’s negotiation course as a short follow-up. With family plans, club projects or scheduling, practice stating needs, asking about priorities and proposing mutually acceptable options.'),('04','考虑下一次暑期直播','Consider a future live summer program','如果 Amy 喜欢讨论、研究项目和教师反馈，再关注 Stanford 下一期。等2027规则公布后核对资格与费用。','If Amy enjoys discussion, research projects and instructor feedback, consider the next Stanford cycle. Check eligibility and fees when 2027 rules appear.')]
for n,z,e,dz,de in stages:
    parts.append('<article><span class="path-number">'+n+'</span><div>'+t(z,e,'h3')+p(dz,de)+'</div></article>')
parts.append('</div><div class="practice">'+t('每周一页“为什么这样选择”笔记','A weekly one-page “Why this choice?” note','h3')+list_items([('发生了什么？只写看得到的行为，不替别人断言内心动机。','What happened? Describe observable behavior without assuming another person’s hidden motives.'),('可能的解释是什么？分别考虑信息、目标、情绪、习惯和社会情境。','What could explain it? Consider information, goals, emotion, habits and social context.'),('还有其他解释吗？哪一条证据会让我改变看法？','What is another explanation? What evidence would change my view?'),('如果要沟通：对方重视什么？我能怎样诚实说明理由，并保留对方拒绝的空间？','For communication: what matters to the other person? How can I explain honestly while leaving room for them to decline?')])+p('这些是个人学习练习。与他人一起做活动时先征得同意，不需要秘密测试同学。','These are personal learning exercises. Get agreement for shared activities; there is no need to secretly test classmates.','small-note')+'</div></section>')

parts.append(section('credentials','07','证书到底证明什么','What the certificate actually establishes'))
credential_rows=[('Coursera / HarvardX','完成平台课程并通过规定测评；通常非学分。','Completion of a platform course and required assessments; generally noncredit.'),('Stanford Pre-Collegiate','完成青少年拓展项目；无大学学分。','Completion of a teen enrichment program; no college credit.'),('eCornell / HBS Online','完成相应的成人专业课程／项目。','Completion of the relevant adult professional course/program.'),('Harvard Extension / Cornell credit','学分课程通常用正式成绩单记录；不能与平台证书混称。','Academic-credit study is normally recorded on an official transcript; distinct from platform certificates.'),('Harvard Extension Graduate Certificate','完成多门研究生课程及成绩要求的正式持续教育证书。','A continuing education credential requiring multiple graduate courses and specified grades.')]
parts.append(table([('类型','Type'),('含义','Meaning')],[[E(title),t(z,e)] for title,z,e in credential_rows],('课程结业、大学学分与学位不是同一种成果','Course completion, university credit and degrees are different outcomes')))
parts.append(p('这些结业证书可以记录学习成果，但不等同于大学录取、学位、校友身份或心理学执业资格。作品集可以准确写：“完成 [提供方] 在 [平台] 的 [课程名称]，并通过测评。”','Completion certificates document learning; they do not establish university admission, a degree, alumni status or psychology licensure. A precise portfolio entry is: “Completed [course] from [provider] on [platform], including required assessments.”'))
parts.append('<div class="course-links">'+link('https://online.yale.edu/courses/introduction-psychology','Yale 对 Coursera 证书的定义','Yale’s definition of its Coursera certificate')+link('https://support.edx.org/hc/en-us/articles/206502008-What-is-a-verified-certificate','edX 认证证书说明','edX verified certificates')+link('https://support.edx.org/hc/en-us/articles/206501438-Can-I-receive-college-credit-or-credit-hours-for-my-course','edX 与学分','edX and academic credit')+'</div>')
parts.append('<div class="source-method">'+t('来源与核查范围','Sources & verification scope','h3')+p('优先采用学校、课程平台和学会的官方页面。每张课程卡都附直接来源与报名入口。所有价格、开课日期和资格均为2026年9月7日核查快照；只看到旧年度资料的项目已注明年份。','Sources prioritize official universities, platforms and the professional association. Each course entry links directly to its evidence and enrollment page. Prices, dates and eligibility are a September 7, 2026 snapshot; older-cycle information is labeled.')+p('未替 Amy 建立账户、报名或付款。未登录才能看到的价格、课内及格分数与个人资格审批，没有用猜测填补。自定进度建议与课程契合度是本指南的判断。','No account, enrollment or payment was made for Amy. Account-specific prices, hidden passing thresholds and individual eligibility approvals are not assumed. Suggested pacing and subject-fit recommendations are this guide’s judgments.')+'</div>')
sources={}
for c in courses:
    for z,e,u in c['links']:
        if u not in sources: sources[u]=(c['school']+' · '+z,c['school']+' · '+e)
parts.append(details('展开所有课程来源索引','Expand the course source index','<ul class="source-index">'+''.join('<li>'+link(u,z,e)+'</li>' for u,(z,e) in sources.items())+'</ul>'))
parts.append('</section>')
parts.append('<footer><div>'+link('/','← 返回 Time Memo','← Back to Time Memo')+'</div>'+p('为 Amy 和家人整理 · 最后核查2026年9月7日','Prepared for Amy and family · Last verified September 7, 2026')+'<button class="print-button" type="button" id="print-guide">'+t('打印／保存当前语言的完整指南','Print / save the full guide in this language')+'</button></footer>')
parts.append('<noscript><p>此页正文默认中文。请启用 JavaScript 切换 English 或中英对照。 / Enable JavaScript to switch to English or bilingual view.</p></noscript></main><script src="app.js"></script></body></html>')
(ROOT / 'index.html').write_text('\n'.join(parts),encoding='utf-8')
print(f'Generated {len(courses)} course/program entries and {len(sources)} course sources; {len((ROOT / "index.html").read_bytes()):,} bytes.')
