window.PROGRAMS = [
  {
    name: "MIT RAISE Day of AI",
    category: "ai",
    link: "https://dayofai.org/",
    fit: { zh: "K–12 分龄材料；约10岁与约13岁均可选对应单元", en: "Age-banded K–12 materials; both around-10 and around-13 learners can choose suitable units" },
    content: { zh: "AI基础、应用、数据与伦理", en: "AI foundations, applications, data, and ethics" },
    format: { zh: "免费课程材料；需成人或教师引导，非固定直播课", en: "Free curriculum requiring adult or teacher facilitation; not a scheduled live class" },
    time: { zh: "模块化；官方未规定家庭周课时", en: "Modular; no official weekly family schedule" },
    price: { zh: "免费", en: "Free" },
    status: { zh: "材料可用；截至2026-09-08", en: "Materials available as of 2026-09-08" },
    backing: { zh: "MIT RAISE参与开发", en: "Developed with MIT RAISE involvement" },
    why: { zh: "免费、分龄且覆盖AI素养与伦理", en: "Free, age-banded coverage of AI literacy and ethics" },
    caveat: { zh: "不是MIT招生、证书或直播学生项目", en: "Not an MIT admissions, certificate, or live student program" }
  },
  {
    name: "Experience AI",
    category: "ai",
    link: "https://experience-ai.org/en-US/",
    fit: { zh: "主要面向11–14岁；较小学习者需成人调整", en: "Designed mainly for ages 11–14; younger learners may need adult adaptation" },
    content: { zh: "机器学习概念、模型训练及应用挑战", en: "Machine-learning concepts, model training, and an app-building challenge" },
    format: { zh: "免费教案、工作表与视频；非直播课", en: "Free lesson plans, worksheets, and videos; not live instruction" },
    time: { zh: "模块化；学生总时长未统一公布", en: "Modular; no single published student duration" },
    price: { zh: "免费", en: "Free" },
    status: { zh: "材料可用；截至2026-09-08", en: "Materials available as of 2026-09-08" },
    backing: { zh: "Raspberry Pi Foundation与Google DeepMind联合开发", en: "Jointly developed by Raspberry Pi Foundation and Google DeepMind" },
    why: { zh: "机构开发的完整免费资源，并有动手挑战", en: "Substantial institution-developed free resources with a hands-on challenge" },
    caveat: { zh: "不要把三周教师培训误作学生课程时长", en: "Do not mistake the three-week educator training for student course length" }
  },
  {
    name: "Code.org AI Curricula",
    category: "ai",
    link: "https://code.org/en-US",
    fit: { zh: "3–5年级与6–8年级有不同单元", en: "Different units serve grades 3–5 and 6–8" },
    content: { zh: "预测、分类、数据整理与AI探索", en: "Prediction, categorization, data sorting, and AI exploration" },
    format: { zh: "免费课程材料；非直播辅导", en: "Free curriculum materials; not live tutoring" },
    time: { zh: "依所选单元而定", en: "Varies by selected module" },
    price: { zh: "免费", en: "Free" },
    status: { zh: "课程可用；品牌命名仍应以官网为准", en: "Curricula available; current branding should be confirmed on the official site" },
    backing: { zh: "Code.org非营利机构课程", en: "Curriculum from the Code.org nonprofit" },
    why: { zh: "覆盖两个目标年龄段，入门门槛低", en: "Covers both target age bands with an accessible entry point" },
    caveat: { zh: "学习体验和时长取决于单元及成人支持", en: "Experience and duration depend on the module and adult support" }
  },
  {
    name: "Create & Learn AI Explorers",
    category: "ai",
    link: "https://www.create-learn.us/ai-for-kids/ai-explorers",
    fit: { zh: "页面标4–8年级；FAQ标4–7年级并要求基础Scratch，8年级需确认", en: "Header says grades 4–8; FAQ says 4–7 and basic Scratch, so grade 8 should confirm fit" },
    content: { zh: "计算机视觉、聊天机器人、游戏AI、机器人、神经网络、伦理与小项目", en: "Computer vision, chatbots, game AI, robotics, neural networks, ethics, and small projects" },
    format: { zh: "2–3人在线直播；有免费入门课", en: "Live online groups of 2–3; free intro available" },
    time: { zh: "12次×55分钟，共11小时", en: "12 × 55-minute sessions; 11 contact hours" },
    price: { zh: "$477常规；页面促销$395.91（Parts 1–3全套）", en: "$477 regular; $395.91 displayed promo for Parts 1–3" },
    status: { zh: "具体班期动态加载，未独立确认", en: "Specific cohort dates load dynamically and were not independently confirmed" },
    backing: { zh: "私人教育机构；师资履历不等于相关机构背书", en: "Private provider; staff biographies do not imply institutional endorsement" },
    why: { zh: "小班直播并覆盖多种AI应用", en: "Small live classes spanning several AI applications" },
    caveat: { zh: "年级与先修说明不一致；付款前确认适配与结账价", en: "Grade and prerequisite wording conflict; confirm fit and checkout price" }
  },
  {
    name: "Create & Learn Python for AI",
    category: "ai",
    link: "https://www.create-learn.us/coding-for-kids/python",
    fit: { zh: "5–10年级；6年级及以下需较多Scratch类经验，7年级以上可从零开始并练习", en: "Grades 5–10; grade 6 and below need substantial Scratch-like experience, while grade 7+ may start without coding if willing to practice" },
    content: { zh: "Python语法、循环、函数、数据结构、OOP、数据与AI API结课项目", en: "Python syntax, loops, functions, data structures, OOP, data, and an AI-API capstone" },
    format: { zh: "2–5人在线直播；有免费入门课", en: "Live online groups of 2–5; free intro available" },
    time: { zh: "16次×70分钟，共18小时40分", en: "16 × 70-minute sessions; 18 hours 40 minutes" },
    price: { zh: "$516常规；页面促销$412.80", en: "$516 regular; $412.80 displayed promo" },
    status: { zh: "具体班期与最终价格以结账页为准", en: "Cohort dates and final price depend on checkout" },
    backing: { zh: "私人教育机构", en: "Private education provider" },
    why: { zh: "适合想系统练Python并获得小班反馈的学习者", en: "Useful for learners seeking structured Python practice and small-group feedback" },
    caveat: { zh: "重点是Python基础，并非深入机器学习理论", en: "Primarily Python foundations, not extensive machine-learning theory" }
  },
  {
    name: "CodeWizardsHQ AI Track",
    category: "ai",
    link: "https://www.codewizardshq.com/ai-track/",
    fit: { zh: "11–18岁；接受Python初学者，10岁不符合该路径标示年龄", en: "Ages 11–18; beginner Python accepted, but age 10 is outside the stated range" },
    content: { zh: "编程入门、自建AI、AI网页应用与结课项目", en: "Programming introduction, building AI, AI-powered web apps, and a capstone" },
    format: { zh: "在线直播，含作业帮助、录播与进度报告", en: "Live online with homework help, recordings, and progress reports" },
    time: { zh: "4门顺序课；每门12次×55分钟，共44小时，不含作业", en: "Four sequential courses; each 12 × 55 minutes, 44 contact hours total excluding homework" },
    price: { zh: "每门$599一次付清或$219×3；四门按当前单门价约$2,396，非已确认套装价", en: "$599 upfront or $219 × 3 per course; four at current upfront rates total about $2,396, not a confirmed bundle" },
    status: { zh: "通常每周；完整秋季日期未确认", en: "Usually weekly; full fall dates not confirmed" },
    backing: { zh: "私人教育机构", en: "Private education provider" },
    why: { zh: "长线、递进式直播路径并提供学习支持", en: "A long, sequential live pathway with learner support" },
    caveat: { zh: "总投入高；退款仅依条款，价格未来可能变化", en: "High total commitment; refunds follow terms and future prices may change" }
  },
  {
    name: "Inspirit AI Creators / AI Pioneers",
    category: "ai",
    link: "https://www.inspiritai.com/ai-program-middle-school",
    fit: { zh: "Creators为4–6年级；Pioneers为5–8年级；无需编程先修", en: "Creators serves grades 4–6; Pioneers grades 5–8; no coding prerequisite" },
    content: { zh: "Scratch或Python、机器学习、NLP聊天机器人、网页应用与社会议题项目", en: "Scratch or Python, machine learning, NLP chatbots, web apps, and social-good projects" },
    format: { zh: "5:1在线直播小组", en: "Live online groups at a 5:1 ratio" },
    time: { zh: "25小时；2026秋季：周二+周三9月15日–11月18日5:00–6:15pm PT；周五9月18日–11月20日7:00–9:30pm PT；周六9月19日–11月21日8:00–10:30am PT；周日9月20日–11月22日12:30–3:00pm PT", en: "25 hours; Fall 2026: Tue + Wed Sep 15–Nov 18, 5:00–6:15pm PT; Fri Sep 18–Nov 20, 7:00–9:30pm PT; Sat Sep 19–Nov 21, 8:00–10:30am PT; Sun Sep 20–Nov 22, 12:30–3:00pm PT" },
    price: { zh: "$1,400（约$56/接触小时）", en: "$1,400 (about $56 per contact hour)" },
    status: { zh: "最早2026年9月15日开课；最终申请截止与剩余名额未核实；冬季为12月19–30日（12月24/25日除外）", en: "Starts as early as Sep 15, 2026; final application deadline and remaining places are unverified; winter runs Dec 19–30 excluding Dec 24/25" },
    backing: { zh: "私人机构；页脚明确非Stanford University官方学术项目", en: "Private provider; footer states it is not an official Stanford University academic program" },
    why: { zh: "适合需要密集指导和项目产出的学习者", en: "A possible fit for learners wanting concentrated guidance and project outputs" },
    caveat: { zh: "毕业院校履历不构成大学背书，也不能证明项目最佳", en: "Alumni biographies are not university endorsement and do not prove the program is best" }
  },
  {
    name: "Veritas AI Trailblazers",
    category: "ai",
    link: "https://www.veritasai.com/ai-trailblazers",
    fit: { zh: "6–8年级；无需先修", en: "Grades 6–8; no prerequisites" },
    content: { zh: "Python、数据分析、回归、分类、神经网络、CNN与伦理", en: "Python, data analysis, regression, classification, neural networks, CNNs, and ethics" },
    format: { zh: "讲授加5:1小组指导和小组项目；官网对小组总人数表述不同，不断言确切总数", en: "Lecture plus 5:1 small-group guidance and a group project; official-page wording differs on total group size, so no exact total is asserted" },
    time: { zh: "25小时；10个周末或暑期2周", en: "25 hours over 10 weekends or 2 summer weeks" },
    price: { zh: "未知；当前费用未核实，需询价", en: "Unknown; current fee not verified—request a quote" },
    status: { zh: "下一期开课时间未核实", en: "Next start date not verified" },
    backing: { zh: "私人机构；未核实为大学运营项目", en: "Private provider; no verified university-operated affiliation" },
    why: { zh: "覆盖较完整的入门机器学习主题与团队项目", en: "Broad introductory machine-learning coverage with a team project" },
    caveat: { zh: "报名或付款前确认实际小组人数与当前价格", en: "Confirm the actual group size and current price before enrolling or paying" }
  },
  {
    name: "The Number Garden Math Circles",
    category: "stem",
    link: "https://thenumbergarden.com/",
    fit: { zh: "3–13岁分龄；约10岁与约13岁需匹配相应组别", en: "Age-banded for ages 3–13; around-10 and around-13 learners need the appropriate group" },
    content: { zh: "规律、猜想、数学谜题与小组讨论", en: "Patterns, conjectures, puzzles, and collaborative math" },
    format: { zh: "波特兰线下数学圈；地址：1717 NE 42nd Ave, Suite 0100B, Portland；可预约免费初访", en: "In-person Portland math circles at 1717 NE 42nd Ave, Suite 0100B, Portland; free introductory visit offered" },
    time: { zh: "秋季周六每周30–60分钟；季节周数需确认", en: "Weekly Saturdays for 30–60 minutes in fall; number of weeks to confirm" },
    price: { zh: "宣传为每季$120–240；并非10/13岁组的确切报价", en: "Advertised at $120–240 per season; not an exact quote for the age-10/13 groups" },
    status: { zh: "2026秋季招生中；截至2026-09-08", en: "Fall 2026 enrolling as of 2026-09-08" },
    backing: { zh: "波特兰独立工作室；未核实外部认证", en: "Independent Portland studio; no external accreditation verified" },
    why: { zh: "本地、低门槛，强调探索式数学思维", en: "Local, accessible practice in exploratory mathematical thinking" },
    caveat: { zh: "先确认高龄组难度、确切周数和价格", en: "Confirm older-group challenge level, exact weeks, and price" }
  },
  {
    name: "The Number Garden Math Mentorship",
    category: "stem",
    link: "https://thenumbergarden.com/",
    fit: { zh: "8岁以上；可做个性化支持或拓展", en: "Ages 8+; intended for individualized support or enrichment" },
    content: { zh: "按学习者需要提供数学支持与拓展", en: "Math support and enrichment tailored to learner needs" },
    format: { zh: "线下个人指导与小组形式，地址：1717 NE 42nd Ave, Suite 0100B, Portland；不保证一对一", en: "In-person individual guidance and small-group format at 1717 NE 42nd Ave, Suite 0100B, Portland; not guaranteed 1:1" },
    time: { zh: "周二或周四下午，每周45–60分钟", en: "Tuesday or Thursday afternoons, 45–60 minutes weekly" },
    price: { zh: "$195/月；可预约免费初访", en: "$195/month; free introductory visit offered" },
    status: { zh: "具体名额需向机构确认", en: "Current openings require confirmation" },
    backing: { zh: "波特兰独立工作室；未核实外部认证", en: "Independent Portland studio; no external accreditation verified" },
    why: { zh: "可针对个人数学目标调整内容", en: "Can adapt content to an individual learner’s math goals" },
    caveat: { zh: "付款前询问实际师生比与教学安排", en: "Ask for the actual student-teacher ratio and structure before paying" }
  },
  {
    name: "AoPS AMC 8 / MATHCOUNTS Basics",
    category: "stem",
    link: "https://artofproblemsolving.com/school/course/mathcounts-basics",
    fit: { zh: "需完成Prealgebra或具同等竞赛准备；按能力而非仅年龄判断", en: "Requires completed Prealgebra or equivalent contest readiness; assess by preparation, not age alone" },
    content: { zh: "数论、代数、计数、概率、几何与逻辑", en: "Number theory, algebra, counting, probability, geometry, and logic" },
    format: { zh: "每周在线直播；传统AoPS Online通常为文字互动，需确认具体班型", en: "Weekly live online class; traditional AoPS Online is usually text-based, so confirm the class format" },
    time: { zh: "12周，每周90分钟；2026年9月18日–12月11日周五4:30–6:00pm PT，9月21日–12月14日周一4:30–6:00pm PT，或9月27日–12月20日周日12:30–2:00pm PT；另有作业，时长未核实", en: "12 weeks, 90 minutes weekly; Sep 18–Dec 11, 2026 Fridays 4:30–6:00pm PT, Sep 21–Dec 14 Mondays 4:30–6:00pm PT, or Sep 27–Dec 20 Sundays 12:30–2:00pm PT; additional homework time unverified" },
    price: { zh: "$415", en: "$415" },
    status: { zh: "2026-09-18、09-21或09-27开课，至12月", en: "Cohorts start Sep 18, Sep 21, or Sep 27, 2026 and run into December" },
    backing: { zh: "AoPS Online School已核实WASC认证", en: "AoPS Online School has verified WASC accreditation" },
    why: { zh: "适合已准备好竞赛型问题解决训练的学习者", en: "Strong option for learners ready for contest-style problem solving" },
    caveat: { zh: "不是通用基础补习；认证不保证个人适配", en: "Not general foundation remediation; accreditation does not guarantee individual fit" }
  },
  {
    name: "AoPS Scholars Middle School Physics Part 1",
    category: "stem",
    link: "https://artofproblemsolving.com/school/course/ms-physics1",
    fit: { zh: "需熟练Prealgebra，无需科学先修；音乐兴趣学习者可能有连接点", en: "Requires Prealgebra proficiency but no prior science; may connect well with an interest in music" },
    content: { zh: "几何光学、波、声音、乐器、家庭实验与模拟", en: "Geometric optics, waves, sound, musical instruments, home experiments, and simulations" },
    format: { zh: "每周在线课；文字或视频形式需确认", en: "Weekly online class; confirm whether text-based or video" },
    time: { zh: "16周，每周90分钟；2026-10-02至2027-02-05，含假期停课", en: "16 weeks, 90 minutes weekly; Oct 2, 2026–Feb 5, 2027 with holiday breaks" },
    price: { zh: "$495", en: "$495" },
    status: { zh: "已核实下一未开课班为周五4:30–6:00pm PT", en: "Next unstarted cohort verified for Fridays, 4:30–6:00pm PT" },
    backing: { zh: "AoPS Online School已核实WASC认证", en: "AoPS Online School has verified WASC accreditation" },
    why: { zh: "把数学、实验与声音/乐器主题结合", en: "Connects math and experiments with sound and musical instruments" },
    caveat: { zh: "需先确认授课媒介与额外作业负担", en: "Confirm the teaching medium and additional homework load" }
  },
  {
    name: "FIRST LEGO League Challenge / ORTOP",
    category: "stem",
    link: "https://ortop.org/programs/fll/",
    fit: { zh: "4–8年级；必须加入或组建本地团队", en: "Grades 4–8; requires joining or forming a local team" },
    content: { zh: "机器人、编程、工程、研究与展示；2026–27主题BIOGLOW", en: "Robotics, coding, engineering, research, and presentation; 2026–27 theme BIOGLOW" },
    format: { zh: "线下团队项目与赛事；ORTOP不负责分配队伍", en: "In-person team project and competitions; ORTOP does not assign children to teams" },
    time: { zh: "创始人资格赛为2026-12-05/06/12/13；州赛2027-01-16，或含17日", en: "Founders qualifiers are Dec 5/6/12/13, 2026; state event Jan 16, 2027, possibly Jan 17" },
    price: { zh: "$285仅为TEAM团队费，不含设备和本地费用；当前全国费用仍需核实", en: "$285 is a TEAM fee excluding equipment and local fees; current national fee still requires verification" },
    status: { zh: "本地页称即将开放，项目页称10月注册；尚未确认开放", en: "Local page says opening soon and program page says October registration; not confirmed open" },
    backing: { zh: "FIRST项目的俄勒冈合作方ORTOP", en: "ORTOP, the Oregon partner for FIRST programs" },
    why: { zh: "提供跨工程、编程和表达的真实团队任务", en: "Offers an authentic team task spanning engineering, coding, and communication" },
    caveat: { zh: "Future Edition地点受地区影响，不保证波特兰场地；需自行落实队伍", en: "Future Edition location depends on geography with no guaranteed Portland venue; family must secure a team" }
  },
  {
    name: "Washington Science Olympiad",
    category: "stem",
    link: "https://washingtonscienceolympiad.com/",
    fit: { zh: "Division A为4–6年级、B为6–9年级；须经学校/团队并符合地区规则", en: "Division A serves grades 4–6 and B grades 6–9; school/team and regional rules apply" },
    content: { zh: "生物、化学、物理、地球科学与工程赛事", en: "Biology, chemistry, physics, earth science, and engineering events" },
    format: { zh: "学校团队赛事", en: "School-team competition" },
    time: { zh: "B/C注册拟于2026-09-18开放；小学活动2026-11-14 9am–noon", en: "B/C registration is scheduled to open Sep 18, 2026; elementary event Nov 14, 2026, 9am–noon" },
    price: { zh: "未知；费用未核实", en: "Unknown; fee not verified" },
    status: { zh: "Clark College小学赛限西南地区学校；俄勒冈儿童资格未确认", en: "Clark College elementary competition is limited to southwest-region schools; Oregon-child eligibility is not confirmed" },
    backing: { zh: "Washington Science Olympiad州级组织", en: "Washington Science Olympiad state organization" },
    why: { zh: "学科覆盖广，适合已有合资格学校团队的学生", en: "Broad subject coverage for students who already have an eligible school team" },
    caveat: { zh: "不能因可驾车到温哥华就推定可参赛；需先核实学校与居住资格", en: "Driving access to Vancouver does not establish eligibility; verify school and residency rules first" }
  },
  {
    name: "OMSI Camps",
    category: "stem",
    link: "https://omsi.edu/camps/",
    fit: { zh: "按4–5与6–8年级等分组；需按具体营队核对", en: "Grouped by bands such as grades 4–5 and 6–8; confirm each camp’s fit" },
    content: { zh: "机器人、科学、法证、动画与自然等季节主题", en: "Seasonal themes including robotics, science, forensics, animation, and nature" },
    format: { zh: "波特兰及附近日营，也有不同长度的过夜营", en: "Portland-area day camps plus overnight camps of varying lengths" },
    time: { zh: "典型日营周一至周五9am–4pm；各营不同", en: "Typical day camps run Monday–Friday, 9am–4pm; varies by camp" },
    price: { zh: "2027价格未知；已过期且时长不同的2026日营/过夜营价格不作为当前比较", en: "2027 price unknown; expired mixed-duration 2026 day/overnight prices are not compared as current" },
    status: { zh: "2026暑期已结束；2027注册显示即将开放", en: "Summer 2026 has ended; 2027 registration is listed as coming soon" },
    backing: { zh: "OMSI科学博物馆教育项目", en: "Education programs from the OMSI science museum" },
    why: { zh: "本地动手科学选择多，适合作为季节性观察项", en: "Varied local hands-on science options worth watching seasonally" },
    caveat: { zh: "目前不是可报名的秋季固定课程；等待2027具体营队与当前报价", en: "Not a currently enrollable fall course; wait for specific 2027 camps and current prices" }
  },
  {
    name: "iUrban Teen Portland",
    category: "stem",
    link: "https://iurbanteen.org/locations/portland/",
    fit: { zh: "活动常面向6–12年级；每场年龄条件需单独核对", en: "Activities often serve grades 6–12; verify eligibility for each event" },
    content: { zh: "面向代表性不足青少年的STEM+Arts活动", en: "STEM+Arts activities for historically underrepresented youth" },
    format: { zh: "波特兰/温哥华非营利活动；形式依项目而定", en: "Nonprofit Portland/Vancouver activities; format varies by program" },
    time: { zh: "未知；2026秋季具体班期未确认", en: "Unknown; no specific fall 2026 cohort confirmed" },
    price: { zh: "常有免费活动；具体场次费用未知", en: "Activities are often free; fee for a specific event is unknown" },
    status: { zh: "观察名单；目前没有已确认可报名的2026秋季课程", en: "Watchlist only; no confirmed enrollment-ready fall 2026 course" },
    backing: { zh: "非营利STEM+Arts机构", en: "Nonprofit STEM+Arts organization" },
    why: { zh: "本地社区型STEM机会，可能降低参与成本", en: "Local community-based STEM opportunities that may reduce cost barriers" },
    caveat: { zh: "不要按种族推断资格；逐项查看年级、对象、费用与开放状态", en: "Do not infer eligibility by race; check each event’s grade, audience, fee, and status" }
  }
];
